// 由 _tools/build_papers.py 產生，請勿手動修改；改 papers.json 或各 md 後重新執行。
window.PAPERS = [
 {
  "id": "Arya2023",
  "type": "Journal Article",
  "year": 2023,
  "title": "The convergence of traditional and digital biomarkers through AI-assisted biosensing: A new era in translational diagnostics?",
  "authors": [
   "Sagar S. Arya",
   "Sofia B. Dias",
   "Herbert F. Jelinek",
   "Leontios J. Hadjileontiadis",
   "Anna-Maria Pappa"
  ],
  "venueShort": "Biosens. Bioelectron.",
  "venue": "Biosensors and Bioelectronics",
  "detail": "Vol. 235 · Article 115387",
  "apa": "Arya, S. S., Dias, S. B., Jelinek, H. F., Hadjileontiadis, L. J., & Pappa, A.-M. (2023). The convergence of traditional and digital biomarkers through AI-assisted biosensing: A new era in translational diagnostics? *Biosensors and Bioelectronics*, *235*, Article 115387. https://doi.org/10.1016/j.bios.2023.115387",
  "doi": "10.1016/j.bios.2023.115387",
  "license": "CC BY",
  "licenseKind": "cc-by",
  "pdf": "Arya_2023_convergence_traditional_digital_biomarkers_AI_biosensing.pdf",
  "translation": "translations/Arya_2023_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n本文是一篇跨領域整合型回顧,主題是「傳統生物標記(traditional biomarkers,例如血液檢驗指標)」與「數位生物標記(digital biomarkers,例如穿戴裝置量測的心率、聲音、動作)」如何透過人工智慧/機器學習整合為單一診斷框架,以推進「照護現場檢測(point-of-care, POC)」的臨床轉譯。作者強調,數位生物標記並非傳統生物標記的線上延伸,而是感測器/裝置持續產生的多維度、跨時間、跨情境的訊號集合。\n\n## 內容重點\n\n- **生物感測器的效能指標**:文章系統整理了生物感測器邁向臨床應用所需評估的關鍵指標,包括靈敏度(sensitivity)、線性動態範圍、偵測極限(LOD)、特異性(specificity)、再現性、臨床切點(clinical cut-off value)、反應時間、抗污損能力與可攜性等。\n- **傳統生物標記的感測技術**:回顧表皮(汗液、組織間液)、淚液、口腔(唾液)、尿液、呼氣等生物體液的感測平台發展。\n- **數位生物標記的感測技術**:整理光學(相機)、聲學(麥克風)、光體積變化描記法(PPG)、觸控螢幕(鍵盤動態)、GPS 等智慧型手機感測器如何被用來擷取健康相關的數位訊號。\n- **AI/ML 在生物感測中的角色**:討論監督式與非監督式學習在生物標記分類、迴歸、訊號降噪中的應用,並列出多個結合 AI 的臨床試驗實例(如巴金森氏症語音分析 i-PROGNOSIS、COVID-19 風險評估 CovidSense)。\n- **兩類標記整合的挑戰**:作者指出,持續性的數位與傳統生物標記監測可能導致「過度診斷」與不必要的醫療介入或恐慌反應,因此需要更精確的後端分析與資料庫(如 DBDP,Digital Biomarker Discovery Pipeline)來降低無效觸發的風險。\n\n## 限制與批判性觀察\n\n- 本文性質偏向廣泛的技術整合型回顧,而非嚴謹的系統性文獻回顧,並未說明明確的檢索策略或納入排除標準,讀者難以評估其引用文獻的代表性與完整度。\n- 文中雖多次提及「個人化醫療」與「使用者賦權」的願景,但整體敘事仍以技術能力為核心,較少著墨使用者如何理解、信任或協商 AI 產生的健康推論結果。\n\n## 與研究主題的關聯\n\n本篇提供了「感測器類型 × AI 演算法 × 臨床應用」的完整技術地圖,適合作為你研究中「技術機制」段落的參考資料;其對「過度監測可能引發不必要恐慌」的討論,也可以呼應你關於使用者詮釋 AI 健康推論的問題意識。",
  "titleZh": "透過 AI 輔助生物感測整合傳統與數位生物標記",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Arya2023/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Bardzell2011",
  "type": "Research Article",
  "year": 2011,
  "title": "Towards a feminist HCI methodology: Social science, feminism, and HCI",
  "authors": [
   "Shaowen Bardzell",
   "Jeffrey Bardzell"
  ],
  "venueShort": "CHI '11",
  "venue": "Proceedings of the SIGCHI Conference on Human Factors in Computing Systems",
  "detail": "pp. 675–684",
  "apa": "Bardzell, S., & Bardzell, J. (2011). Towards a feminist HCI methodology: Social science, feminism, and HCI. In *Proceedings of the SIGCHI Conference on Human Factors in Computing Systems* (pp. 675–684). ACM. https://doi.org/10.1145/1978942.1979041",
  "doi": "10.1145/1978942.1979041",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "BardzellBardzell_2011_Towards_Feminist_HCI_Methodology.pdf",
  "translation": "translations/BardzellBardzell_2011_中文摘要整理.md",
  "translationMd": "## 這篇論文在做什麼\n\n這篇是 Shaowen Bardzell 在 2010 年提出「Feminist HCI」一詞後,隔年與 Jeffrey Bardzell 合寫的**方法論補完之作**。2010 年那篇奠基文獻雖然開創了 feminist HCI 這個空間,並提出一組「女性主義互動特質」,但並未講清楚:實際做研究時,一套「女性主義的」方法論究竟長什麼樣子?本文正是要回答這個問題——作者систематически梳理「女性主義社會科學」數十年來在科學哲學辯論中累積的立場,把這些立場「翻譯」進 HCI 的研究實作語彙,最後提出一套初步、開放性的 feminist HCI 方法論輪廓。\n\n## 核心論證:客觀性與價值不是對立的\n\n全文的哲學起點,是傳統實證主義科學(主張價值應該被排除在科學之外)與後實證主義科學(主張社會文化價值必然嵌入科學實踐之中)之間的張力。作者借用 Quine 以降的科學哲學傳統指出:科學理論永遠無法單靠資料完全決定,社會與實用考量本就無可避免地與科學糾纏在一起。女性主義科學哲學正是在這個後實證主義脈絡下,進一步證明「性別」實際上深刻影響了科學的過程與產出——因此,追求「客觀」與追求「社會/道德進步」並非互斥的兩件事,而是可以、也應該同時以同等嚴謹的態度追求。\n\n## 三個常見誤解的澄清\n\n作者在文中特別點名幾個容易被混淆的概念,這幾點對於理解「什麼才算 feminist HCI」相當關鍵:\n\n- **女性主義不是單一整體,而是複數的「諸女性主義(feminisms)」**——本文聚焦的是科學哲學脈絡下的女性主義方法論學者,而非文學批評或政治行動主義脈絡的女性主義。\n- **Feminist HCI 不等於「研究性別與運算」**——性別與運算(gender and computing)是一個研究「議題領域」,而 feminist HCI 的判準是研究方法與女性主義思想之間是否有實質連結,兩者不能劃等號。這也是延續、並具體化了 Bardzell (2010) 提出但未講清楚的判準。\n- **女性主義不偏好質性研究勝過量性研究**——作者強調女性主義關心的是「是否以人們自身的方式再現他們」,而非特定研究方法本身;量性與質性研究都可能被扭曲濫用,也都可能被嚴謹且具反身性地運用。\n\n## 女性主義社會科學的三個共同哲學承諾\n\n作者歸納出跨越不同女性主義流派的三個共通立場:(1) 拒絕「科學是價值中立」這個實證主義核心教條;(2) 堅持所有人類經驗都是有效的、不應被排除在理解之外;(3) 致力於確保「性別」持續作為一個被正視的研究分析軸線,而不被科學論述悄悄抹除。\n\n## 提出的 Feminist HCI 方法論輪廓\n\n在梳理完哲學基礎後,作者提出一套**暫定、非規範性**的方法論要素,包括:與研究參與者建立同理式關係、聚焦理解其經驗;研究者/實踐者的自我揭露(揭露自己在世界中的位置、目標與立場);研究核心問題與目標的共同建構(由研究者與研究對象協作決定,而非單向設定);採用多元/混合方法以支持辯證式的知識生產;以及持續的反身性(不斷自我質問研究是否真正實現了女性主義、改善人類生活品質的企圖)。作者明確強調這份輪廓**不是操作規範或處方**,而是一套可依具體研究情境調整取捨的參考架構。\n\n## 對你研究的意義\n\n這篇論文提供了一個關鍵判準工具,可以用來檢驗你資料夾中其他質性研究(例如 Chen 2026 的台灣經期追蹤研究、Kang 2025 的 PCOS 自我民族誌、Sultana et al. 2025 的 Socheton 研究)是否/在何種程度上符合「feminist HCI 方法論」的核心要素——例如它們是否讓研究參與者共同建構研究問題與詮釋、研究者是否揭露自身立場、是否採取多元方法支持辯證式知識生產。這也是你在論述自己研究方法論定位時,可以直接援引的理論基礎文獻之一,與你先前提出的「使用者如何詮釋/協商 AI 健康推論」這個問題意識高度呼應——因為這正是本文所主張的「與研究參與者建立同理式關係、聚焦理解其經驗」的具體體現。",
  "titleZh": "邁向一套 Feminist HCI 方法論:社會科學、女性主義與 HCI",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Bardzell2011/筆記.md",
  "notesMd": ""
 },
 {
  "id": "CampoWoytuk2020",
  "type": "Research Article",
  "year": 2020,
  "title": "Touching and being in touch with the menstruating body",
  "titleZh": "觸摸與貼近經期中的身體",
  "authors": [
   "Nadia Campo Woytuk",
   "Marie Louise Juul Søndergaard",
   "Marianela Ciolfi Felice",
   "Madeline Balaam"
  ],
  "venueShort": "CHI '20",
  "venue": "Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems",
  "detail": "Paper 344",
  "apa": "Campo Woytuk, N., Søndergaard, M. L. J., Ciolfi Felice, M., & Balaam, M. (2020). Touching and being in touch with the menstruating body. In *Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems* (Paper 344). ACM. https://doi.org/10.1145/3313831.3376471",
  "doi": "10.1145/3313831.3376471",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "3313831.3376471.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/CampoWoytuk2020/筆記.md",
  "notesMd": ""
 },
 {
  "id": "CampoWoytuk2023",
  "type": "Pictorial",
  "year": 2023,
  "title": "Tactful feminist sensing: Designing for touching vaginal fluids",
  "titleZh": "有分寸的女性主義感測：為觸摸陰道分泌物而設計",
  "authors": [
   "Nadia Campo Woytuk",
   "Joo Young Park",
   "Jan Maslik",
   "Marianela Ciolfi Felice",
   "Madeline Balaam"
  ],
  "venueShort": "DIS '23",
  "venue": "Proceedings of the 2023 ACM Designing Interactive Systems Conference",
  "detail": "",
  "apa": "Campo Woytuk, N., Park, J. Y., Maslik, J., Ciolfi Felice, M., & Balaam, M. (2023). Tactful feminist sensing: Designing for touching vaginal fluids. In *Proceedings of the 2023 ACM Designing Interactive Systems Conference*. ACM. https://doi.org/10.1145/3563657.3595966",
  "doi": "10.1145/3563657.3595966",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "3563657.3595966.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/CampoWoytuk2023/筆記.md",
  "notesMd": ""
 },
 {
  "id": "CampoWoytuk2025",
  "type": "Research Article",
  "year": 2025,
  "title": "Toward feminist ways of sensing the menstruating body",
  "titleZh": "邁向以女性主義方式感測經期中的身體",
  "authors": [
   "Nadia Campo Woytuk",
   "Anupriya Tuli",
   "Joo Young Park",
   "Laia Turmo Vidal",
   "Deirdre Tobin",
   "Anuradha Reddy",
   "Beatrice Vincenzi",
   "Jan Maslik",
   "Marianela Ciolfi Felice",
   "Madeline Balaam"
  ],
  "venueShort": "CHI '25",
  "venue": "Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems",
  "detail": "17 pages",
  "apa": "Campo Woytuk, N., Tuli, A., Park, J. Y., Turmo Vidal, L., Tobin, D., Reddy, A., Vincenzi, B., Maslik, J., Ciolfi Felice, M., & Balaam, M. (2025). Toward feminist ways of sensing the menstruating body. In *Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3706598.3713466",
  "doi": "10.1145/3706598.3713466",
  "license": "CC BY-NC",
  "licenseKind": "cc-by-nc",
  "pdf": "3706598.3713466.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/CampoWoytuk2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Cao2024",
  "type": "Research Article",
  "year": 2024,
  "title": "\"I deleted it after the overturn of Roe v. Wade\": Understanding women's privacy concerns toward period-tracking apps in the post Roe v. Wade era",
  "titleZh": "「羅訴韋德案被推翻後我就刪了」：後羅訴韋德時代女性對經期追蹤 App 的隱私顧慮",
  "authors": [
   "Jiaxun Cao",
   "Hiba Laabadli",
   "Chase Mathis",
   "Rebecca Stern",
   "Pardis Emami-Naeini"
  ],
  "venueShort": "CHI '24",
  "venue": "Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems",
  "detail": "22 pages",
  "apa": "Cao, J., Laabadli, H., Mathis, C., Stern, R., & Emami-Naeini, P. (2024). \"I deleted it after the overturn of Roe v. Wade\": Understanding women's privacy concerns toward period-tracking apps in the post Roe v. Wade era. In *Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3613904.3642042",
  "doi": "10.1145/3613904.3642042",
  "license": "CC BY",
  "licenseKind": "cc-by",
  "pdf": "3613904.3642042.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Cao2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Chen2026",
  "type": "Research Article",
  "year": 2026,
  "title": "Intimate data performativity: Taiwanese women's self-care practices with menstrual tracking apps",
  "authors": [
   "Wei-Ping Chen"
  ],
  "venueShort": "Asian J. Commun.",
  "venue": "Asian Journal of Communication",
  "detail": "Advance online publication",
  "apa": "Chen, W.-P. (2026). Intimate data performativity: Taiwanese women's self-care practices with menstrual tracking apps. *Asian Journal of Communication*. Advance online publication. https://doi.org/10.1080/01292986.2026.2686753",
  "doi": "10.1080/01292986.2026.2686753",
  "license": "CC BY 4.0",
  "licenseKind": "cc-by",
  "pdf": "Chen_2026_intimate_data_performativity_Taiwanese_women_menstrual_tracking.pdf",
  "translation": "translations/Chen_2026_中文摘要整理.md",
  "criticalForm": {
   "path": "intimate-data-queer/01_文獻探討/critical-form/Chen2026/01_抽取草稿.md",
   "stage": "抽取草稿 · 待你確認"
  },
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Chen2026/筆記.md",
  "translationMd": "## 摘要重點\n\n本研究提出「親密資料展演性(intimate data performativity)」作為分析概念,主張台灣女性在使用經期追蹤 App 時,是在「演算法系統、文化期待、身體感知經驗」三者交會處進行協商,而非單純被賦權或被規訓的二元對立。研究透過日記研究法結合深度訪談,共訪問 16 位參與者,歸納出三個相互交織的面向:(1) 具身知識生產中的演算法協商——使用者一方面接受預測系統的建議,一方面仍保有詮釋主導權;(2) 追蹤實踐被整合進自我最適化(self-optimization)practice 中,同時展現「賦權」與「規訓」的矛盾動態;(3) 資料分享重構親密關係——經期 App 中介了照護與監控之間帶有性別意涵的動態關係。\n\n## 理論脈絡\n\n作者指出既有文獻多將使用者定位為「被賦權」或「被規訓」兩種角色之一,忽略了使用者在操作這些技術時實際呈現的矛盾、曖昧策略;且既有研究多聚焦西方脈絡與規範框架,對非西方文化情境下(治療式自我照護、性別期待、數位健康治理各有不同樣貌)的追蹤實踐理解有限。台灣作為研究場域的特殊之處在於:東亞文化中「經期是隱私、甚至帶有羞恥感」的觀念,與逐漸盛行的西方式健康自我最適化論述並存,兩者交織出獨特的具身資料實踐張力。\n\n## 方法重點\n\n- 研究對象為 16 位透過 PTT、Dcard 招募的台灣女性,條件為 20 歲以上、已使用經期追蹤 App 至少一個月;皆為未婚、無子女、自認異性戀順性別女性。\n- 資料收集結合「日記研究法」(參與者透過作者自建的 Facebook Messenger 聊天機器人,即時記錄使用 App 當下的螢幕截圖與詮釋、情緒反應,為期約兩週)與「半結構式深度訪談」(依日記內容延伸討論初始使用動機、日常追蹤慣例、詮釋歷程等)。\n- 最常被提及的三款 App 為「小月曆(Little Moon Calendar)」、Flo、Clover,三者在文化定位上各有差異(如小月曆走「可愛」在地化路線、Flo 強調醫療權威性)。\n\n## 主要發現\n\n- **演算法協商**:使用者對 App 的評分/預測系統既有「詮釋不確定性」(不完全信任演算法給出的判讀),也出現「知識論重新定位」(逐漸依演算法重新理解自己的身體)與「策略性挪用」(選擇性採用演算法功能來回答自己關心的具身問題)。\n- **自我最適化的矛盾動態**:參與者將經期追蹤廣泛整合進身體管理、情緒調節等自我最適化實踐中,展現出「賦權」與「自我規訓」同時並存的張力。\n- **資料分享重構親密關係**:多數參與者認為經期資料過於私密而不願分享,資料分享行為本身呈現出「選擇性揭露」與「相互監控」並存的雙重動態,尤其涉及伴侶是否可以/應該追蹤對方經期時,常被討論為「照護」或「監控」的模糊地帶。\n\n## 限制與批判性觀察(作者自述)\n\n- 研究樣本為特定背景的 16 位台灣女性(未婚、無子女、異性戀順性別),研究洞見無法涵蓋母親、酷兒族群、或已放棄使用追蹤工具者的具身經驗。\n- 日記研究期間較短,僅能捕捉與演算法系統的「即時協商」,難以呈現使用者與追蹤技術關係隨時間演變的長期軌跡。\n- 作者建議未來可進行跨東亞社會的比較研究,檢視「演算法協商、自我最適化要求、關係性資料實踐」這三個面向在不同東亞脈絡(各自有不同的月經污名程度與監管環境)下的具體展現,但強調需謹慎處理各地脈絡差異,避免預設區域同質性。\n\n## 與研究主題的關聯\n\n這篇是目前蒐集到的文獻中,**與你的研究主題最直接對應**的一篇:它明確以台灣女性為研究對象,並提出「親密資料展演性」這個概念工具,直接處理「使用者如何在演算法推論與自身具身經驗之間協商」這個核心問題意識,可作為你研究架構中理論與方法論的重要參照點,也適合與 Kang et al. (2025, PCOS 自我民族誌)、Hudig & Singh (2025, 生育追蹤資料流動) 並列討論。",
  "titleZh": "親密資料的展演性:台灣女性使用經期追蹤 App 的自我照護實踐",
  "criticalFormMd": "## 1. Reference\n\nChen, W.-P. (2026). Intimate data performativity: Taiwanese women's self-care practices with menstrual tracking apps. *Asian Journal of Communication*. Advance online publication. https://doi.org/10.1080/01292986.2026.2686753\n\n（❓ 注意：抽取到的全文只有 DOI 跟「Published online: 11 Jun 2026」，沒有看到 volume/issue/頁碼，判斷是線上優先出版（advance online publication），套用 APA 第七版線上優先出版格式。等正式排版出來、有 volume/issue/頁碼後要更新這條）\n\n## 2. Scope of Research and Major Background\n\n**Scope**：[[menstrual tracking apps]]、[[algorithmic imaginaries]]、[[data performativity]]、[[gendered neoliberal health governance]]、[[qualified self]]\n\n**Background**：既有演算法健康科技研究大致分成兩派——一派強調資料蒐集與自我認識帶來的賦權（Neff & Nafus, 2016; Ruckenstein & Schüll, 2017），另一派則批判追蹤科技複製監控結構與規訓機制（Lupton, 2016; Sharon, 2017）。專門針對經期追蹤 App 的研究則多聚焦西方脈絡與法規環境（Fox & Epstein, 2020; Stardust et al., 2024），使得經期追蹤 App 在不同文化脈絡（如台灣同時存在東亞經期忌諱與西方自我優化論述）下如何運作，仍是研究空缺。\n\n## 3. Research Problem(s), Aim and Objectives\n\n**Problem**：既有「賦權／規訓」二元框架，是否足以捕捉台灣女性使用經期追蹤 App 時真實、矛盾、游移的實踐樣貌？\n\n（原文以三個具體 RQ 呈現，附在下方 Objectives 對照，Problem 是我從中歸納出的上位問題，建議你核對這樣歸納有沒有偏掉原意）\n\n**Aim**：建立 [[intimate data performativity]]（親密資料展演性）作為概念透鏡，用以理解台灣女性在演算法系統、文化期待與具身經驗交會之處如何協商經期追蹤 App。\n\n**Objectives**：\n1. 探討台灣女性如何將經期追蹤 App 同時當作身體知識工具，以及強化性別期待的規訓技術來使用\n2. 檢視日常使用實踐究竟複製還是挑戰主流的女性身體與生殖健康理解\n3. 藉由台灣案例，對科技、性別、具身性在當代數位文化中的更廣泛問題提供啟發\n\n## 4. Methodology and Steps\n\n**Methodology**：[[質化數位方法]]（qualitative digital methods），結合日記研究法與深度訪談\n\n**Steps**：\n- 透過 PTT、Dcard 招募 16 位台灣女性（20 歲以上、使用經期追蹤 App 至少一個月，皆為異性戀、未婚、無子女的順性別女性）\n- 以 Facebook Messenger 聊天機器人進行 2023/8/25–9/12 的數位日記蒐集，共 118 篇日記（平均每人 7.4 篇）\n- 進行 2023/9/3–9/10、每次 1.5–3 小時的半結構式訪談，訪談前已先看過該受訪者的日記內容\n- 採用理論導向的 [[thematic analysis]]，以 [[abductive method]] 在三個理論領域（演算法想像、性別化新自由主義健康治理、資料展演性）與經驗資料間反覆比對、開放新興主題\n\n## 5. Results, Discussion and Conclusion\n\n**Results**：分析浮現三個主要面向——(1) 演算法協商於具身知識生產中的角色（不確定性、認知重新定向、策略性挪用）；(2) 追蹤整合進自我優化實踐（身體/情緒/生殖規劃），呈現賦權與控制並存的矛盾動態；(3) 資料分享重構親密關係，經期 App 中介伴侶間照顧與監控的性別動態\n\n**Discussion**：這些發現呼應了研究問題——顯示既有「賦權／規訓」二元框架無法涵蓋使用者實際展現的矛盾實踐：使用者同時擁抱演算法權威又保有詮釋自主權、追求優化又抵抗全面監控、展演傳統女性氣質又為身體自主開創空間\n\n**Conclusion**：本研究提出 [[intimate data performativity]] 作為新概念框架，包含三個相互關聯的維度：[[epistemological performativity]]（認識論展演性）、[[regulatory performativity]]（規訓展演性）、[[relational performativity]]（關係展演性）。並建議未來研究可延伸至其他東亞社會做比較、納入更多元的使用者（如已為人母者、酷兒群體、已放棄追蹤者），並採用縱貫研究設計\n\n## 6. Significance and Learnings\n\n**信度**：研究從 16 位受訪者的日記＋訪談雙重資料出發，用溯因式主題分析在理論框架與經驗資料間反覆校準；作者也明確反思自身研究者位置（引用 Finlay, 2002），推理鏈完整、論證過程與資料之間邏輯自洽\n\n**重要性**：填補既有經期追蹤研究多聚焦西方脈絡的空缺，提出的概念框架可延伸至其他文化脈絡做比較研究，同時對批判資料研究、女性主義科技研究、健康傳播三個領域都有貢獻\n\n## 7. Questions（agent 草擬，推論／僅供參考，非定論）\n\n- 本研究樣本僅涵蓋異性戀、未婚、無子女的順性別女性，若納入已婚、已生育、酷兒群體或已放棄追蹤的使用者，「親密資料展演性」的三個維度是否仍然成立，還是會浮現新的維度？\n- 認識論／規訓／關係三種展演性之間，是否存在互相強化或抵銷的交互作用？本文目前是並列討論三者，尚未深入處理彼此的動態關係\n\n（讀完後，你自己想追問的問題留在這裡）",
  "guideMd": "## Introduction｜緒論\n描述台灣女性使用經期追蹤 App 時，同時面對「躺平」的犬儒氛圍與自我優化的療癒文化。指出既有研究多落在「賦權」或「規訓」二元框架，且集中在西方脈絡，提出三個研究問題。\n\n## Literature review｜文獻探討\n- **演算法想像與具身追蹤**：以 Bucher 的演算法想像說明使用者如何理解預測系統，以及資料化如何把身體經驗轉成數據。\n- **性別化的新自由主義健康治理**：回顧「後女性主義健康主義」等概念，說明健康被當成個人責任，femtech 把生殖資料商品化。\n- **資料展演性與質化自我**：說明資料不只是再現，而是在使用中建構自我；引入 Humphreys 的 qualified self。\n- **中介的具身性**：整合以上三個框架，提出後續實證分析的三個面向。\n\n## Methodology｜研究方法\n- **研究脈絡**：說明經期 App 仰賴自我回報，並觀察 PTT、Dcard 與媒體如何討論這類 App。\n- **研究設計**：數位日記法加深度訪談。\n- **參與者**：透過 PTT、Dcard 招募 16 位使用過一個月以上的女性。\n- **數位日記**：用 Messenger 聊天機器人蒐集 7–10 天、共 118 則使用紀錄與截圖。\n- **訪談與分析**：1.5–3 小時半結構訪談，以理論導向的主題分析、溯因推理整理資料。\n\n## Results and discussion｜結果與討論\n- **數位神諭**：使用者一面接受演算法預測，一面保有詮釋權；App 產生預測性、解釋性、規範性三種身體知識。\n- **優化的矛盾**：追蹤延伸到情緒管理、生產力與生育規劃，同時帶來賦權與依賴。\n- **分享親密資料**：選擇性揭露是一種抵抗；與伴侶分享時，照顧與監控交織在一起。\n- **親密資料展演性**：歸納出認識論、規範、關係三個維度，作為本文的概念框架。\n\n## Conclusion｜結論\n說明概念框架對演算法想像、健康治理與資料展演性三個理論脈絡的貢獻，提出對健康傳播與數位健康素養的建議，並承認樣本僅限異性戀、未婚女性等限制，建議後續做東亞比較與縱貫研究。",
  "notesMd": ""
 },
 {
  "id": "Chowdhury2025",
  "type": "Preprint",
  "year": 2025,
  "title": "From literature to 'ReWA': Discussing reproductive well-being in HCI",
  "authors": [
   "Hafsah Mahzabin Chowdhury",
   "Sharifa Sultana"
  ],
  "venueShort": "arXiv",
  "venue": "arXiv preprint (submitted to CSCW '26)",
  "detail": "30 pages",
  "apa": "Chowdhury, H. M., & Sultana, S. (2025). *From literature to 'ReWA': Discussing reproductive well-being in HCI* [Preprint]. arXiv. https://doi.org/10.48550/arXiv.2507.01121",
  "doi": "10.48550/arXiv.2507.01121",
  "license": "arXiv",
  "licenseKind": "unknown",
  "pdf": "ChowdhurySultana_2025_ReWA_reproductive_wellbeing_HCI.pdf",
  "translation": "translations/ChowdhurySultana_2025_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n這是一篇大範圍文獻回顧,整合 HCI、CSCW/社會運算、ICTD(資通訊科技與發展)、數位/公共衛生、AI for well-being 等領域中,2015–2025 年間發表的 147 篇同儕審查論文(初始篩選超過 300 篇),藉此描繪「生殖福祉(reproductive well-being)」研究的技術景觀。作者主張生殖福祉深受文化、宗教、性別、政治脈絡交織影響,但現有技術設計卻多半反映狹隘的西方中心假設。\n\n## 主要發現\n\n- 歸納出三波研究主題演進:**第一波**聚焦早期資訊近用與教育;**第二波**轉向文化敏感度與隱私;**第三波**則是 AI 整合與具政策意識的設計。\n- 指出研究與技術設計中持續存在的排除性缺口:男性與非二元性別使用者、移民、以及**全球南方(Global South)**使用者長期被排除或代表性不足。\n- 特別指出一個罕被討論的缺口:除了使用者本人之外,其他利害關係人角色(如丈夫與家庭成員、家務幫傭、助產士等)在生殖福祉研究中幾乎完全缺席。\n\n## ReWA 框架:六大設計取向\n\n作者據此提出 ReWA(Reproductive Well-being for All)框架,包含六個設計取向:\n1. **地點、文化與歷史**——資料與工具設計須反映使用者所處的地理、文化與歷史脈絡的政治性。\n2. **多元發聲與能動性(Polyvocality and Agency)**——基礎設施與工具應納入多元敘事與價值觀,而非單一標準化敘事。\n3. **理性觀(Rationality)**——挑戰主流生殖科技過度倚賴西方科學/醫療/演算法理性(強調量化、風險預測與標準化)的預設。\n4. **時間性(Temporality)**\n5. **角色分配(Distributive Roles)**\n6. **方法論(Methodology)**\n\n## 限制與批判性觀察(作者自述)\n\n- 檢索僅限英語同儕審查文獻,可能排除非英語、灰色文獻或在地/草根設計實踐的重要洞見。\n- 儘管涵蓋多個全球區域,現有文獻本身仍嚴重偏向全球北方(尤其美國)脈絡,限制了跨社會文化情境的可類推性。\n- 作者也坦言,身心障礙者、跨性別光譜使用者、原住民使用者等交織性(intersectional)經驗過於複雜,難以被目前的主題框架完整分類呈現。\n\n## 與研究主題的關聯\n\n這是目前蒐集文獻中**範圍最廣、最適合作為文獻回顧地圖**的一篇——它系統性指出「全球南方使用者(含多數亞洲地區)長期被排除」正是這個領域公認的缺口,直接支持你研究的正當性與定位;其「六大設計取向」框架也可作為你討論亞洲女性資料設計研究時的理論鷹架,例如檢視現有 femtech 工具是否符合「地點/文化/歷史」與「多元發聲」等取向。",
  "titleZh": "從文獻到 ReWA:HCI 領域中的生殖福祉討論",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Chowdhury2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Coskun2023",
  "type": "Survey Article",
  "year": 2023,
  "title": "Data sensemaking in self-tracking: Towards a new generation of self-tracking tools",
  "titleZh": "自我追蹤中的資料意義建構：邁向新一代自我追蹤工具",
  "authors": [
   "Aykut Coşkun",
   "Armağan Karahanoğlu"
  ],
  "venueShort": "IJHCI",
  "venue": "International Journal of Human–Computer Interaction",
  "detail": "Vol. 39, No. 12 · pp. 2339–2360",
  "apa": "Coşkun, A., & Karahanoğlu, A. (2023). Data sensemaking in self-tracking: Towards a new generation of self-tracking tools. *International Journal of Human–Computer Interaction*, *39*(12), 2339–2360. https://doi.org/10.1080/10447318.2022.2075637",
  "doi": "10.1080/10447318.2022.2075637",
  "license": "Taylor & Francis",
  "licenseKind": "restricted",
  "pdf": "2022_IJHCI_Data_Sensemaking_in_Self_Tracking.pdf",
  "translation": "translations/Coskun_Karahanoglu_2022_中文摘要整理.md",
  "translationMd": "## 摘要\n\nHCI 研究者對「自我追蹤者如何從自我追蹤工具(Self-Tracking Tools, STT)的數據中獲得有意義的洞見」這個課題興趣日增,但文獻中始終缺乏一個連貫、整合、專門處理「如何設計支持自我追蹤者意義建構(sensemaking)實踐的工具」的資料來源。為填補此缺口,作者系統性回顧了 2021 年以前發表於 HCI 領域的 91 篇文獻,歸納出自我追蹤者經歷的**四種資料意義建構模式**(自我校準、資料擴增、資料處理、領悟),以及支持這些實踐的**四項設計啟示**(客製化追蹤體驗、引導式意義建構、協作式意義建構、透過自我實驗學習意義建構)。作者並提出一份九個方向的研究議程,最後主張這份成果可作為設計者與研究者理解、研究、設計「自我追蹤者資料意義建構實踐」的分析性資訊來源。\n\n## 背景\n\n- 人類自古便有以日記、個人紀錄進行自我報告的傳統;近年隨科技進展,活動追蹤器、智慧手錶等「自我追蹤工具(STT)」大量出現,能收集從步數到睡眠品質、血糖、心率等複雜的個人數據。\n- HCI 研究者過去多聚焦「使用者如何監測行為」「STT 應具備哪些支持追蹤的特質」「如何為新一代 STT 設計提供準則」等課題。\n- 近期研究開始挑戰「STT 僅是量化行為的裝置」這種古典觀點,批評「過度量化」「過度數位化」會損害人類經驗的內在價值,轉而主張 STT 應支持使用者從數據中獲得質性、主觀、社會性的意義,幫助使用者達成「更全面地理解自己」與「可執行的行為決策」,而不只是數字的堆疊。\n- 這個「從量化轉向獲取洞見」的取徑,促使研究者開始探討使用者的資料意義建構實踐(data sensemaking practices)。作者引用資料/資訊/知識/智慧金字塔(DIKW pyramid, Rowley, 2007)說明:原始資料本身抽象而無意義,唯有經過人的認知投入,才能逐步轉化為資訊、知識、理解,乃至智慧。\n- **意義建構的核心挑戰**:使用者常誤讀數據(如把睡眠時心率波動誤判為健康問題,實則可能只是壓力或喝水不足所致);當數據呈現的意義與使用者預期不符時,會產生挫折感,甚至導致對數據與自我追蹤活動的脫離(disengagement)。\n- 過去雖有少數研究以「意義建構」為核心焦點,但多侷限於單一追蹤情境(如睡眠或體能活動),難以將發現遷移至其他情境;其餘研究則多半只把意義建構當作眾多發現之一附帶提及。文獻始終缺乏一個連貫、整合的專門資料來源,這正是本文試圖填補的缺口。\n\n## 研究問題\n\n本文以系統性文獻回顧處理以下三個研究問題:\n\n1. 自我追蹤者如何理解(make sense of)自己的自我追蹤數據?\n2. 在這個意義建構過程中,他們遭遇哪些挑戰?\n3. 為克服這些挑戰、支持自我追蹤者的意義建構實踐,STT 的設計應有哪些啟示?\n\n## 研究方法\n\n- **回顧類型**:仿照 Xiao & Watson (2019) 的系統性文獻回顧程序,並參考 PRISMA scoping(Moher et al., 2009)流程。\n- **資料庫與關鍵字**:檢索 ACM Digital Library、IEEE Explore、Web of Science、Scopus 四個資料庫;以「sensemaking 相關詞」(sensemaking, sense-making, make/made sense, meaning, meaningful, meaningfulness)交叉「自我追蹤相關詞」(self-tracking, personal informatics, quantified self)進行檢索,檢索時間為 2021 年 1 月,涵蓋 2020 年以前發表的文獻。\n- **篩選流程(PRISMA 流程圖)**:初始檢索共得 722 篇(ACM 518、Web of Science 74、IEEE Explore 12、Scopus 118)→ 排除短篇通訊、社論、未完成研究、無法下載文獻(n=69)→ 移除重複文獻(n=197,剩 456 篇)→ 篩選階段排除未探討自我追蹤/個人資訊學脈絡數據的文獻(n=220,剩 236 篇)→ 資格審查階段排除僅將關鍵字用於描述結果「合理性」或粗略提及數據意義而未連結意義建構的文獻(n=145)→ **最終納入 91 篇文獻**。\n- **分析方法**:採用 Braun & Clarke (2006) 的反覆式主題分析(thematic analysis),結合歸納與演繹編碼。兩位作者各自每輪讀 10 篇並編碼,依三個預設類別編碼(對應三個研究問題):(i) 意義建構活動、(ii) 促進與阻礙這些活動的因素/挑戰、(iii) 支持這些活動的設計啟示。第一輪得到 236 行編碼,第二輪歸納為 23 種活動類型,第三輪整合為 7 個活動類別,並歸入 4 種意義建構模式。\n\n**語料庫概況**:研究主題最多為疾病/病況管理(n=19)、體能活動追蹤(n=17)、心理健康與情緒健康(n=10);資料收集方法以訪談最多(n=49),其次為線上資料內容分析(n=12)、觀察(n=9)、共創工作坊(n=9)、焦點團體(n=4)、日記法(n=2);僅 15 篇為長期追蹤研究;**幾乎所有研究樣本皆為西方族群(美國、歐洲、澳洲),僅 2 篇招募東方族群(南韓)參與者**。\n\n## 結果\n\n### 四種資料意義建構模式(可重疊、非線性)\n\n1. **自我校準(Self-calibration)**:設定/調整追蹤目標、辨識相關追蹤面向、獲取領域知識(如學習醫學術語)。自問:「我該追蹤什麼數據?我要怎麼使用這些數據?」\n2. **資料擴增(Data augmentation)**:以主觀觀察、感受為自動生成的數位數據加註(annotation),使數據更豐富、更貼近真實生活經驗。自問:「這些數據是否足以讓我獲得有意義的洞見?我該如何用自己的經驗與感受豐富它?」\n3. **資料處理(Data handling)**:包含「資料整理(curation)」(合併不同來源數據、移除離群值、修補缺漏)與「辨識探索相關資訊」(尋找數據中的變化與模式)。自問:「我該如何讓資料準備好被我詮釋?」\n4. **領悟(Realization)**:包含「推理與反思」(尋求數據模式的合理解釋,常與他人、醫療專業者協作反思)與「對峙(confrontation)」(決定確認、協商,或脫離這個新理解)。自問:「這些數據告訴我什麼?為什麼?這正常嗎?我同意數據告訴我的事嗎?」\n\n作者特別強調:這四種模式並非使用者必須依序完成的線性步驟,而是彼此可重疊、且因人因情境而異的離散類別。\n\n### 四項設計啟示\n\n1. **客製化追蹤體驗**:讓使用者自行決定追蹤參數、允許手動資料收集與加註、提供細緻而非常模化(如避免僅用「平均、高於平均」等標籤)的視覺呈現、支持正念反思。\n2. **引導式意義建構**:透過反思性提示與問題、提供目標達成預測、解釋數字與術語的意義、透明呈現追蹤數值的計算邏輯、協助辨識不同數據類型間的關聯與異常成因。\n3. **協作式意義建構**:建立線上追蹤社群、允許使用者與醫療照護者共同反思數據、同時兼顧隱私保護(如抽象化呈現、預設分享規則)。\n4. **透過自我實驗學習意義建構**:讓使用者形成並測試關於自己的假設,將焦點從「數字」轉向「經驗與敘事」,支持行為改變的決策。\n\n## 討論\n\n- **理論貢獻一**:四種意義建構模式提供了一個整體性視角,可協助設計研究者分析使用者洞見、辨識特定使用者群體在哪個模式/活動上遭遇最大困難;也可作為設計全新追蹤需求(如向兒童溝通心率問題)的起點,採取「以活動為導向」而非「以工具為導向」的設計流程;還可用於「重新想像」既有追蹤情境(例如新確診 vs. 確診 20 年的糖尿病患者,兩者在意義建構需求上截然不同)。\n- **理論貢獻二**:四項設計啟示屬於「行為層次」的一般性設計考量,適用於問題界定與發想階段,而非具體設計方案的規定性指示;其下更具體的設計建議(見原文表 4–7)則可提供更明確的操作指引。作者也提醒:由於四種模式彼此互聯而非線性,設計者的創造力在「收斂與發散」這些知識時仍扮演關鍵角色。\n\n### 九項未來研究議程\n\n1. 探討 STT 的實用性與享樂性角色的平衡——自我追蹤是高度情緒化的活動,設計應同時兼顧「完成追蹤功能」與「支持使用者的因應/療癒需求」。\n2. 正視協作式意義建構實踐——從「以自我為中心」轉向親子、教練—運動員、病患—醫療照護者等集體追蹤實踐,需進一步研究資料隱私與信任建立。\n3. 邁向後設資訊學(meta-informatics)——隨追蹤數據種類日增,需要能自動整合、分析多來源數據的工具。\n4. 在「量化自我」與「質化自我」間取得平衡——多數 STT 提供的是「可執行的數據」,但應同時容許使用者以文字、語音等方式進行更主觀質性的自我詮釋。\n5. 探討追蹤者在意義建構中的不同角色——「資料科學家型」「經驗學習者型」「協商者型」三種角色。\n6. 探索資料意義建構的新形式——開發數字、圖表以外更多元的呈現方式,涵蓋視障者、兒童、資料素養有限者等群體。\n7. **改善資料意義建構研究的包容性**——語料庫中幾乎全數為西方族群樣本,作者明確呼籲未來應有跨文化、超越 WEIRD(西方、受過教育、工業化、富裕、民主)族群的研究。\n8. 進行更多長期追蹤研究——91 篇中僅 15 篇為長期研究。\n9. 邁向自我追蹤資料意義建構理論——本文視為建構此理論的早期一步,邀請後續研究者延伸。\n\n### 結論\n\n本文透過系統性回顧過去約 20 年間 91 篇文獻,歸納出自我追蹤者在資料意義建構過程中的經驗、掙扎與挑戰,提出四種意義建構模式與四項設計啟示,並規劃一份研究議程,期望協助設計者與研究者更分析性、更連貫地理解自我追蹤者的意義建構實踐,以指引新一代自我追蹤工具的設計。\n\n## 與研究主題的關聯\n\n這篇文獻的**第七項研究議程(跨文化/超越 WEIRD 族群)**與**語料庫組成(91篇中僅2篇東方族群樣本)**,直接證實了「東亞脈絡缺席」不只適用於經期/PMS 文獻,而是**整個自我追蹤 HCI 領域的結構性缺口**。此外,四種意義建構模式(尤其是「領悟」模式中的「推理反思」與「對峙」)與四項設計啟示,提供了可直接遷移套用於生理週期數據情境的分析框架——可作為研究問題「生理週期數據如何轉換為可理解、可執行的行動建議」的理論起點,建議與 [Chen_2026](Chen_2026_中文摘要整理.md) 提出的「親密資料展演性」概念、[Kang_2025](Kang_2025_中文摘要整理.md) 的 PCOS 自我民族誌並列討論,檢視此一般性框架在生理週期數據的週期性、污名化、難以量化等特殊性下是否需要修正或延伸。",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Coskun2023/筆記.md",
  "notesMd": ""
 },
 {
  "id": "GomezOrtega2022",
  "type": "Research Article",
  "year": 2022,
  "title": "Reconstructing intimate contexts through data donation: A case study in menstrual tracking technologies",
  "titleZh": "透過資料捐贈重建親密情境：以經期追蹤科技為例",
  "authors": [
   "Alejandra Gómez Ortega",
   "Jacky Bourgeois",
   "Gerd Kortuem"
  ],
  "venueShort": "NordiCHI '22",
  "venue": "Nordic Human-Computer Interaction Conference",
  "detail": "12 pages",
  "apa": "Gómez Ortega, A., Bourgeois, J., & Kortuem, G. (2022). Reconstructing intimate contexts through data donation: A case study in menstrual tracking technologies. In *Nordic Human-Computer Interaction Conference (NordiCHI '22)*. ACM. https://doi.org/10.1145/3546155.3546646",
  "doi": "10.1145/3546155.3546646",
  "license": "CC BY",
  "licenseKind": "cc-by",
  "pdf": "3546155.3546646.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/GomezOrtega2022/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Grimme2024",
  "type": "Research Article",
  "year": 2024,
  "title": "My data, my choice, my insights: Women's requirements when collecting, interpreting and sharing their personal health data",
  "titleZh": "我的資料、我的選擇、我的洞見：女性蒐集、詮釋與分享個人健康資料的需求",
  "authors": [
   "Sophie Grimme",
   "Susanna Marie Spoerl",
   "Susanne Boll",
   "Marion Koelle"
  ],
  "venueShort": "CHI '24",
  "venue": "Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems",
  "detail": "18 pages",
  "apa": "Grimme, S., Spoerl, S. M., Boll, S., & Koelle, M. (2024). My data, my choice, my insights: Women's requirements when collecting, interpreting and sharing their personal health data. In *Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3613904.3642851",
  "doi": "10.1145/3613904.3642851",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "3613904.3642851.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Grimme2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Hudig2025",
  "type": "Research Article",
  "year": 2025,
  "title": "Intimate data sharing: Enhancing transparency and control in fertility tracking",
  "authors": [
   "Anna Ida Hudig",
   "Jatinder Singh"
  ],
  "venueShort": "CHI '25",
  "venue": "Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems",
  "detail": "24 pages",
  "apa": "Hudig, A. I., & Singh, J. (2025). Intimate data sharing: Enhancing transparency and control in fertility tracking. In *Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3706598.3714089",
  "doi": "10.1145/3706598.3714089",
  "license": "CC BY 4.0",
  "licenseKind": "cc-by",
  "pdf": "Hudig_Singh_2025_intimate_data_sharing_fertility_tracking.pdf",
  "translation": "translations/Hudig_Singh_2025_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n生育追蹤 App 廣泛用於自我監測月經週期與其他生殖/性健康面向,但其資料的高度私密性,使「資料如何被使用」成為重大疑慮。本研究採混合方法:(1) 對八款生育追蹤產品進行網路流量監測,分析其資料傳輸對象;(2) 以問卷(n=162)了解使用者對資料分享的態度與影響因素;(3) 透過焦點團體與使用者共同設計十項強化資料透明度與控制的具體機制。\n\n## 方法重點\n\n- **資料流監測**:架設 Raspberry Pi 監測存取點(MAP),攔截並記錄八款生育追蹤 App/裝置(含經期 App、穿戴裝置、體溫計、荷爾蒙檢測套組)的網路封包,分析其連線的 IP 位址、所屬組織與國家,並區分「設定」「互動使用」「閒置」「客製化隱私設定」四種情境下的傳輸差異。\n- **問卷調查**:招募 162 位受訪者(不限是否為生育追蹤使用者),以情境化問卷探討受訪者對不同資料類型、不同利害關係人(App 業者、廣告商、雇主、保險公司、醫師、伴侶、學術研究單位、公共衛生部門)的資料分享意願,並測試「資料去識別化」對分享意願的影響。\n- **焦點團體共同設計**:四場線上焦點團體(共 15 位參與者),依「選擇、設定、使用、停用後」四階段的產品生命週期,與使用者共同發想透明度與控制機制。\n\n## 主要發現\n\n- 八款產品平均各自連線至 13.5 個不同組織、橫跨 7.5 個國家,部分連線對象位於美國、俄羅斯、烏克蘭、摩爾多瓦等資料保護規範與英國/歐盟不同的地區。\n- 資料傳輸模式與使用者的實際互動行為(如輸入經期日期、性行為紀錄、完成荷爾蒙檢測分析)在時間點上高度吻合,顯示使用者輸入的親密資料很可能在輸入當下即被傳輸出去。\n- 受訪者的資料分享意願因「利害關係人」而有極大差異:對醫師(僅 11% 完全不願分享)與學術研究單位(僅 12% 完全不願分享)相對開放;對線上廣告平台(88% 完全不願分享)與雇主(65% 完全不願分享)則高度抗拒。\n- 影響分享意願最重要的三項因素依序為:資料收集的具體目的、資料是否去識別化、資料會被分享給哪些第三方;地點與儲存時長則被認為相對不重要。\n- 資料去識別化能顯著提升對多數利害關係人的分享意願(尤其是保險公司與公共衛生部門),但對「線上廣告平台」幾乎沒有效果——部分受訪者明確表示即使去識別化也不願支持這類商業用途。\n\n## 共同設計出的十項機制\n\n研究團隊與使用者共同發展出十項涵蓋「選擇前、設定時、使用中、停用後」四階段的透明度與控制機制,包括:App 商店簡明摘要與短影片說明、獨立第三方比較平台、逐步同意流程與開關式權限設定、可選擇性同意條款特定段落、即時資料分享通知與彈性拒絕選項、資料匯出與遷移工具、停用後資料處理說明與刪除保證等。\n\n## 限制與批判性觀察(作者自述)\n\n- 資料流監測僅涵蓋八款產品,無法代表整個市場全貌;且因資料多為加密傳輸,僅能透過 IP 位址與中繼資料(metadata)推論可能的接收方,無法確認實際傳輸內容。\n- 問卷與焦點團體樣本以歐洲、年輕、高教育程度、自認具技術素養的女性為主,可能無法完整反映更多元背景(如開發中國家、非西方文化脈絡、跨性別者)使用者的觀點與需求。\n- 作者強調,將資料治理責任完全交由使用者「自我管理」可能造成過度負擔,呼籲業者、監管機構、消費者保護單位應共同承擔更多責任,而非僅靠透明度/控制機制解決問題。\n\n## 與研究主題的關聯\n\n本篇直接補上了你研究架構中「Data → AI inference ↔ Human interpretation」這一環目前少被觸及的部分:它具體指出資料在使用者輸入的當下即可能被傳輸給第三方,揭露了「使用者對自己親密資料實際流向的認知」與「資料生態系統實際運作方式」之間的巨大落差,可作為你論述「女性身體經驗與 AI 健康推論之間需要更多協商空間」的實證基礎,也可與 Kang et al. (2025) 的第一人稱經驗研究相互呼應。",
  "titleZh": "生育追蹤中的親密資料分享:強化透明度與控制",
  "criticalFormMd": null,
  "guideMd": "## 1 Introduction｜緒論\n從健康、情緒等親密資料被大量蒐集談起，指出生育追蹤工具的資料流向不透明，提出三個研究目標：了解資料分享現況、使用者的分享偏好，以及和使用者共同設計透明度與控制機制。\n\n## 2 Background, Context, and Related Work｜背景與相關研究\n- **2.1 行動 App 與連網裝置的隱私**：整理過度索取權限、網路追蹤、控制選項不足等既有問題。\n- **2.2 生育追蹤器與資料考量**：定義生育追蹤器（App、穿戴裝置、檢測套組），說明其資料高度私密帶來的風險。\n- **2.3 更廣泛的批判**：回顧設計缺乏包容性的批評，例如忽略非生育需求者、性別少數與文化差異。\n- **2.4 透明度與控制**：界定兩個概念，並指出把資料治理交給使用者「自我管理」的局限。\n\n## 3 Methodology｜研究方法\n三段式混合方法：\n- **3.1 資料流監測**：架設監測點，攔截 8 款生育追蹤產品的網路傳輸。\n- **3.2 問卷**：162 位受訪者，以情境題探詢對不同對象分享資料的意願。\n- **3.3 焦點團體**：4 場共 15 人，依產品生命週期共同設計機制。\n- **3.4 研究倫理**：經倫理委員會核准，敏感題目可不答，資料去識別化。\n\n## 4 Understanding Data Flows｜資料流分析結果\n8 款產品平均連線到 13.5 個組織、橫跨 7.5 個國家；資料傳輸的時間點與使用者輸入行為高度吻合，顯示親密資料可能在輸入當下就被送出。\n\n## 5 Understanding User Preferences and Attitudes｜使用者偏好與態度\n分享意願主要取決於接收對象：對醫師與學術研究較開放，對廣告商與雇主高度抗拒。去識別化能提高多數對象的分享意願，但對廣告商幾乎無效。多數人希望知道蒐集了哪些資料、用在哪裡。\n\n## 6 Realising Data Transparency and Control｜共同設計的機制\n焦點團體先討論擔憂，再依「選擇、設定、使用、停用後」四個階段共同設計十項機制（例如 App 商店摘要、逐步同意、即時分享通知、資料匯出與刪除保證），最後討論這些機制對使用者造成的負擔。\n\n## 7 Discussion｜討論\n綜合三項研究的發現並對照既有文獻；說明產品數量與樣本組成的限制；延伸討論使用者自主分享、第三方角色、性別議題與機制落地的未來方向。\n\n## 8 Conclusion｜結論\n總結資料實際流向與使用者期待之間的落差，主張業者、監管單位與消費者保護機構應共同承擔責任，而不是只靠使用者自己管理。",
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Hudig2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Ibrahim2024",
  "type": "Research Article",
  "year": 2024,
  "title": "Tracking during Ramadan: Examining the intersection of menstrual and religious tracking practices among Muslim women in the United States",
  "authors": [
   "Zaidat Ibrahim",
   "Novia Nurain",
   "James Clawson"
  ],
  "venueShort": "CHI '24",
  "venue": "Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems",
  "detail": "19 pages",
  "apa": "Ibrahim, Z., Nurain, N., & Clawson, J. (2024). Tracking during Ramadan: Examining the intersection of menstrual and religious tracking practices among Muslim women in the United States. In *Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3613904.3642374",
  "doi": "10.1145/3613904.3642374",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "Ibrahim_2024_Tracking_During_Ramadan_menstrual_religious_tracking.pdf",
  "translation": "translations/Ibrahim_2024_Ramadan_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n許多穆斯林女性會同時使用多種個人資訊化(Personal Informatics, PI)工具,來支持自己的宗教/靈性福祉與健康管理。本研究聚焦居住於美國、正在齋戒(Ramadan)月的穆斯林女性,探討她們的宗教追蹤與健康追蹤實踐如何交織——因為依伊斯蘭教義,經期中的女性可豁免齋戒等特定宗教活動,使得「宗教追蹤」與「經期追蹤」在實務上難以分割。研究採用為期一個月的日記研究法,搭配半結構式訪談,對象為 9 位觀察齋戒月的穆斯林女性。\n\n## 方法重點\n\n- 招募 10 位參與者,9 位完成研究(1 位中途退出)。所有參與者皆追蹤經期並持守齋戒。\n- 資料收集方式:每位參與者完成 10 篇「每日日誌(Daily Log)」與 2 篇「反思日誌(Reflection Log)」,間隔約每 2–3 天記錄一次,涵蓋整個經期週期的不同階段;日誌完成後,研究者依內容設計個人化的半結構式訪談問題(訪談總時長 410 分鐘,平均每人 46 分鐘)。\n- 研究對象背景多元:參與者出生於美國境外者約占全美穆斯林人口的 65%,橫跨至少 68 個不同國籍,作者刻意選擇美國作為研究場域以捕捉伊斯蘭信仰內部的多元詮釋與實踐差異。\n\n## 主要發現(概述)\n\n- 揭露驅動參與者追蹤行為的宗教與健康雙重動機。\n- 說明社會角色(如家庭、職場角色)如何影響追蹤實踐的方式與內容。\n- 指出參與者在同時追蹤「靈性健康」與「身體健康」這兩個常相互競爭的目標時所遭遇的具體衝突與挑戰。\n\n## 限制與批判性觀察(作者自述)\n\n- 研究採用線上數位日記(Qualtrics)招募參與者,這意味著樣本本身即偏向對科技較熟悉、較容易取用科技的族群。\n- 參與者並非同時期加入研究,部分參與者需在齋戒月尾聲——宗教活動通常最密集的時期——同時應付研究要求與宗教實踐,可能是造成中途退出或參與度下降的原因之一。\n- 研究未特別詢問參與者「信仰實踐年資」(是自幼信仰或後來皈依),而信仰實踐的時間長短可能影響追蹤行為模式,作者建議未來研究可納入此變項。\n- 作者提醒,若要將本研究發現套用至美國以外的穆斯林人口,須額外考量當地文化與家庭脈絡對宗教實踐的社會建構方式可能不同。\n\n## 與研究主題的關聯\n\n本篇雖以美國穆斯林女性(而非亞洲本地女性)為研究對象,但由於全球穆斯林人口高度集中於亞洲(尤其南亞、東南亞),其研究方法(結合宗教實踐與經期追蹤的交織分析)與核心問題意識(工具設計如何/是否涵蓋特定文化與信仰脈絡下的具身需求)對你研究「亞洲女性 × 數據 × 設計」議題具有高度參照價值,尤其可作為思考「文化/宗教脈絡如何形塑追蹤工具設計需求」的方法論範例。",
  "titleZh": "齋戒月期間的追蹤實踐:美國穆斯林女性經期與宗教追蹤的交會",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Ibrahim2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Jain2024",
  "type": "Research Article",
  "year": 2024,
  "title": "Platforming PCOS treatment online: FemTech logics of care",
  "titleZh": "將 PCOS 治療平台化：FemTech 的照護邏輯",
  "authors": [
   "Taru Jain",
   "Preeti Mudliar"
  ],
  "venueShort": "CHI '24",
  "venue": "Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems",
  "detail": "18 pages",
  "apa": "Jain, T., & Mudliar, P. (2024). Platforming PCOS treatment online: FemTech logics of care. In *Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3613904.3642882",
  "doi": "10.1145/3613904.3642882",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "3613904.3642882.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Jain2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Kang2025",
  "type": "Research Article",
  "year": 2025,
  "title": "Towards hormone health: An autoethnography of long-term holistic tracking to manage PCOS",
  "authors": [
   "Daye Kang",
   "Jingjin Li",
   "Gilly Leshed",
   "Jeffrey M. Rzeszotarski",
   "Xi Lu"
  ],
  "venueShort": "CHI '25",
  "venue": "Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems",
  "detail": "20 pages",
  "apa": "Kang, D., Li, J., Leshed, G., Rzeszotarski, J. M., & Lu, X. (2025). Towards hormone health: An autoethnography of long-term holistic tracking to manage PCOS. In *Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3706598.3713619",
  "doi": "10.1145/3706598.3713619",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "Kang_2025_PCOS_autoethnography_holistic_tracking.pdf",
  "translation": "translations/Kang_2025_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n多囊性卵巢症候群(PCOS)是一種常見的荷爾蒙失調疾病,影響全球約 11–13% 育齡女性,症狀高度個人化,包含月經不規律、痤瘡、體重增加等。現有的自我追蹤工具(如經期追蹤 App)多半是為「規律經期的健康女性」設計,對 PCOS 患者所需的「個人化」與「長期整體性追蹤」支援不足。本研究的第一作者本身是 PCOS 患者,以自我民族誌(autoethnography)方法,記錄自己長達十個月的整體性自我追蹤經驗,藉此揭露管理 PCOS 過程中在醫療、社會文化、時間、技術、空間五個面向所遭遇的挑戰,並據此提出更具包容性與永續性的追蹤工具設計建議。\n\n## 方法重點\n\n- 採用自我民族誌(autoethnography)研究方法,由第一作者本人作為研究對象,以第一人稱視角詳細記錄十個月期間使用多種追蹤工具(經期 App、飲食紀錄、症狀日誌等)管理 PCOS 的真實經驗與工具轉換過程。\n\n## 主要發現(五大挑戰面向)\n\n- **醫療面**:以生育為導向設計的經期追蹤工具,對 PCOS 患者(其經期本身即不規律甚至無排卵)常導致誤判或錯誤解讀。\n- **社會文化面**:飲食追蹤工具難以適應不同文化脈絡下的飲食習慣與社交情境。\n- **時間面**:旅行等生活變動會打斷既有的追蹤節奏,造成資料斷點與追蹤困難。\n- **技術/組織面**:因應不同需求而混用多種工具導致資料分散、彈性追蹤方式反而帶來技術與整理上的負擔。\n- **空間面**:在不同生活空間中維持一致的追蹤慣性本身就是一項挑戰。\n\n## 設計啟示\n\n作者據此提出的設計建議包括:追蹤範圍應從單純的生育導向,擴展到涵蓋代謝健康;提供更細緻(granular)的追蹤選項;支援更具彈性的追蹤方式與跨情境行為改變支援等。\n\n## 限制與批判性觀察(作者自述)\n\n- 自我民族誌方法本質上僅反映單一研究者(第一作者)的個人經驗,未必能代表其他 PCOS 患者的多元處境。\n- 第一作者的社經與文化背景(具高等教育、醫療資源可近性、技術設計專業、南韓文化脈絡)可能無法反映其他社經或文化背景下 PCOS 患者的真實挑戰,例如部分開發中國家女性仍以紙本記錄經期而非數位工具。\n- 作者建議未來研究應納入更多元的 PCOS 患者(可搭配參與式設計方法),並可考慮採用「群體自我民族誌(group autoethnography)」以獲得多重研究者視角。\n\n## 與研究主題的關聯\n\n本篇雖非「數據→AI→健康推論」的技術性文獻,但提供了極具價值的對照視角:它從使用者第一人稱經驗出發,具體呈現「當追蹤工具的預設健康推論(如以生育為中心的經期演算法)與患者真實身體經驗不符時」所產生的落差與挫折,可直接支持你研究中「使用者如何理解與協商 AI 健康推論」這條核心問題意識。",
  "titleZh": "PCOS 長期整體自我追蹤之自我民族誌研究",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Kang2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "MaciasAlonso2024",
  "type": "Review",
  "year": 2024,
  "title": "Definitions of digital biomarkers: A systematic mapping of the biomedical literature",
  "authors": [
   "Ana Karen Macias Alonso",
   "Julian Hirt",
   "Tim Woelfle",
   "Perrine Janiaud",
   "Lars G. Hemkens"
  ],
  "venueShort": "BMJ HCI",
  "venue": "BMJ Health & Care Informatics",
  "detail": "Vol. 31 · Article e100914",
  "apa": "Macias Alonso, A. K., Hirt, J., Woelfle, T., Janiaud, P., & Hemkens, L. G. (2024). Definitions of digital biomarkers: A systematic mapping of the biomedical literature. *BMJ Health & Care Informatics*, *31*, Article e100914. https://doi.org/10.1136/bmjhci-2023-100914",
  "doi": "10.1136/bmjhci-2023-100914",
  "license": "CC BY",
  "licenseKind": "cc-by",
  "pdf": "MaciasAlonso_2024_definitions_digital_biomarkers.pdf",
  "translation": "translations/MaciasAlonso_2024_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n本文並非在研究某個疾病的預測模型,而是回頭追問一個根本問題:「數位生物標記(digital biomarker)」這個詞在生醫文獻中到底是怎麼被定義的?作者系統性檢索 PubMed 中所有標題或摘要含有「digital biomarker(s)」一詞的文章(檢索至 2023 年 3 月),共 415 篇中有 128 篇文章提供了明確定義,並依 FDA 的 BEST(Biomarkers, EndpointS and other Tools)框架,拆解每個定義是否涵蓋「資料類型」「收集方式」「用途」三個組成要素。\n\n## 主要發現\n\n- 127 篇文章給出了 127 種彼此不同的定義,僅有 2 篇文字完全重複——顯示這個詞目前高度缺乏共識。\n- 僅約 18%(23 篇)的定義同時涵蓋「資料類型、收集方式、用途」三要素,多數定義只片面涉及其中一到兩項。\n- 兩大監管機構——歐洲藥品管理局(EMA)與美國食品藥物管理局(FDA)——對「digital biomarker」一詞的定義也彼此不一致,FDA 的官方指引甚至並未正式使用這個詞彙。\n- 作者建議未來可透過 Delphi study(專家共識法)建立一個較為一致的定義。\n\n## 限制與批判性觀察\n\n- 檢索僅限單一資料庫(PubMed),且僅以「digital biomarker」作為關鍵詞搜尋,作者自陳這可能低估了工程/資訊領域文獻(如 IEEE、ACM 資料庫)中對此詞彙的多元定義方式。\n- 文章篩選與資料萃取主要由單一審閱者執行,僅在不確定時才交叉確認,存在主觀分類偏誤的風險。\n\n## 與研究主題的關聯\n\n本篇的核心價值不在於回答「digital biomarker 是什麼」,而在於揭露這個詞本身就是一個尚未穩定、仍在被協商中的概念建構。這直接支持了一個延伸提問:「數位資料要滿足什麼條件,才有資格被解讀為具有健康意義?」——這正是目前領域公認的定義真空,也是你的研究可以切入的空間。",
  "titleZh": "數位生物標記定義之系統性 Mapping",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/MaciasAlonso2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Mehrnezhad2021",
  "type": "Research Article",
  "year": 2021,
  "title": "Caring for intimate data in fertility technologies",
  "titleZh": "生育科技中的親密資料照護",
  "authors": [
   "Maryam Mehrnezhad",
   "Teresa Almeida"
  ],
  "venueShort": "CHI '21",
  "venue": "Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems",
  "detail": "11 pages",
  "apa": "Mehrnezhad, M., & Almeida, T. (2021). Caring for intimate data in fertility technologies. In *Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3411764.3445132",
  "doi": "10.1145/3411764.3445132",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "3411764.3445132.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Mehrnezhad2021/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Olyanasab2024",
  "type": "Review",
  "year": 2024,
  "title": "Leveraging machine learning for personalized wearable biomedical devices: A review",
  "authors": [
   "Ali Olyanasab",
   "Mohsen Annabestani"
  ],
  "venueShort": "J. Pers. Med.",
  "venue": "Journal of Personalized Medicine",
  "detail": "Vol. 14, No. 2 · Article 203",
  "apa": "Olyanasab, A., & Annabestani, M. (2024). Leveraging machine learning for personalized wearable biomedical devices: A review. *Journal of Personalized Medicine*, *14*(2), Article 203. https://doi.org/10.3390/jpm14020203",
  "doi": "10.3390/jpm14020203",
  "license": "CC BY",
  "licenseKind": "cc-by",
  "pdf": "Olyanasab_Annabestani_2024_ML_personalized_wearable_biomedical_devices.pdf",
  "translation": "translations/Olyanasab_Annabestani_2024_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n本文回顧「個人化穿戴式生醫裝置 × 機器學習」相關文獻,依感測原理將裝置分為三大類:生電類(bio-electrical,例如心電圖 ECG、肌電圖 EMG、腦電圖 EEG)、生阻抗與電化學類(bio-impedance / electrochemical,例如血糖、電解質監測)、機電類(electro-mechanical,例如動作與活動偵測)。作者透過 Scopus、Nature、IEEE Xplore 等資料庫,以「Personalized + Wearable + Machine Learning」為關鍵詞檢索,整理約 60 篇案例研究,說明機器學習如何提升這些裝置的個人化偵測能力。\n\n## 主要發現\n\n- 整理的案例涵蓋巴金森氏症、癲癇、壓力、恐慌發作、脫水、傷口癒合、睡眠呼吸中止、跌倒偵測等多種健康應用。\n- 多數研究回報的準確率落在 75%–100% 之間,其中約 78.5% 的裝置被作者標記為具有「個人化(personalized)」特性,即以個別使用者的資料進行模型訓練或校正。\n\n## 限制與批判性觀察\n\n- 本文並未採用 PRISMA 流程或提供正式的排除文章數統計,檢索與篩選過程的透明度不足,較接近敘事式回顧而非嚴謹的系統性回顧。\n- 「個人化(personalized)」一詞在文中並未有明確的操作型定義,認定標準似乎主要依作者主觀判斷;多數所謂的個人化系統,實質上僅是「以個別受試者資料訓練或校正模型」,並未涉及使用者主觀詮釋或情境差異的考量。\n- 表格中所引用的部分案例研究樣本數極小(如 N=4、N=5、N=7),卻仍被列為驗證高準確率的成功案例,存在僅報告成功案例、未呈現失敗或陰性結果的偏誤疑慮。\n\n## 與研究主題的關聯\n\n本篇技術性內容豐富,適合作為「感測器 → 機器學習 → 健康推論」技術機制段落的案例庫來源,但因其「個人化」概念操作定義鬆散、方法學嚴謹度偏弱,不建議在定義層面或方法論層面直接依賴此文作為權威來源。",
  "titleZh": "機器學習於個人化穿戴式生醫裝置之應用回顧",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Olyanasab2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Park2024",
  "type": "Research Article",
  "year": 2024,
  "title": "Critiquing menstrual pain technologies through the lens of feminist disability studies",
  "titleZh": "以女性主義障礙研究視角批判經痛科技",
  "authors": [
   "Joo Young Park",
   "Stacy Hsueh",
   "Nadia Campo Woytuk",
   "Xuni Huang",
   "Marianela Ciolfi Felice",
   "Madeline Balaam"
  ],
  "venueShort": "CHI '24",
  "venue": "Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems",
  "detail": "15 pages",
  "apa": "Park, J. Y., Hsueh, S., Campo Woytuk, N., Huang, X., Ciolfi Felice, M., & Balaam, M. (2024). Critiquing menstrual pain technologies through the lens of feminist disability studies. In *Proceedings of the 2024 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3613904.3642691",
  "doi": "10.1145/3613904.3642691",
  "license": "CC BY-NC",
  "licenseKind": "cc-by-nc",
  "pdf": "3613904.3642691.pdf",
  "translationMd": null,
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Park2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "PitDosSantos2024",
  "type": "Review",
  "year": 2024,
  "title": "Machine learning applied to digital phenotyping: A systematic literature review and taxonomy",
  "authors": [
   "Marília Pit dos Santos",
   "Wesllei Felipe Heckler",
   "Rodrigo Simon Bavaresco",
   "Jorge Luis Victória Barbosa"
  ],
  "venueShort": "CHB",
  "venue": "Computers in Human Behavior",
  "detail": "Vol. 161 · Article 108422",
  "apa": "Pit dos Santos, M., Heckler, W. F., Bavaresco, R. S., & Barbosa, J. L. V. (2024). Machine learning applied to digital phenotyping: A systematic literature review and taxonomy. *Computers in Human Behavior*, *161*, Article 108422. https://doi.org/10.1016/j.chb.2024.108422",
  "doi": "10.1016/j.chb.2024.108422",
  "license": "Elsevier",
  "licenseKind": "restricted",
  "pdf": "PitDosSantos_2024_ML_digital_phenotyping_systematic_review.pdf",
  "translation": "translations/PitDosSantos_2024_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n本篇為嚴謹的系統性文獻回顧(systematic mapping study),依 Petersen et al. (2008) 的方法學,檢索 11 個涵蓋資訊工程與醫學領域的資料庫(含 IEEE Xplore、ACM DL、PubMed、Scopus、Web of Science 等),檢索至 2023 年 11 月,初始命中 2,860 篇文章,經去重、標題摘要篩選、三階段(three-pass)全文審查後,最終納入 124 篇文章,回答六個研究問題,涵蓋機器學習技術、資料類型、裝置、本體論(ontology)與研究挑戰。\n\n## 方法重點\n\n- 使用 Parsifal 工具管理篩選流程,並採用 Keshav (2007) 提出的「三階段閱讀法」(先讀標題/摘要/引言 → 再看圖表 → 最後精讀全文)作為納入判斷依據。\n- 明確列出納入(IC1–IC3)與排除(EC1–EC4)標準,並說明檢索字串未涵蓋「digital biomarker」「passive sensing」等相關同義詞,可能排除部分相關文獻——這點被作者自己列為限制。\n\n## 主要發現\n\n- 納入研究的樣本數變異極大:平均樣本數約 7,910 人,但中位數僅 117 人,標準差高達約 39,628,顯示少數大型研究(如公開資料集)大幅拉高平均值,多數研究實際樣本量偏小。\n- 最主要的研究挑戰依序為:資料品質與規模不足(21 篇明確提及需要更大樣本)、類別不平衡(imbalanced class)、遺失值處理、因果推論困難、自陳資料偏誤、裝置電力與技術限制等。\n- 傳統機器學習方法(邏輯迴歸、SVM、隨機森林)仍是主流選擇,原因除了資料量限制外,也與臨床端對模型可解釋性的需求有關;而樣本量與資料不平衡問題,會進一步限制深度學習方法的可用性。\n- 沒有任何一篇納入研究使用或提出本體論(ontology)架構來組織資料概念,作者認為這是未來可發展的方向。\n\n## 限制與批判性觀察(作者自述)\n\n- 檢索字串僅鎖定「digital phenotype」「digital phenotyping」兩個核心詞及其同義詞,未納入「digital biomarker」「mobile sensing」「passive sensing」等相關但不同的術語,作者承認這可能導致遺漏未直接使用「phenotype」一詞、但實質相關的重要文獻。\n- 篩選與分類過程主要由單一研究者執行,檢索字串的組成本身也可能存在人為疏漏,屬於任何 mapping study 常見的限制。\n\n## 與研究主題的關聯\n\n這是本次蒐集文獻中方法學最嚴謹的一篇系統性回顧,其對「小樣本」「資料不平衡」「自陳偏誤」等挑戰的系統整理,適合直接支撐你論述中「AI 從數位資料推論健康狀態」這個技術環節目前實際面臨的限制與不確定性。",
  "titleZh": "機器學習於數位表型之系統性文獻回顧與分類法",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/PitDosSantos2024/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Raj2026",
  "type": "Preprint",
  "year": 2026,
  "title": "User perspectives of an mHealth app for premenstrual syndrome (PMS) self-management: A qualitative study",
  "authors": [
   "Pankhuri Raj",
   "Nhung Huyen Hoang",
   "Zilu Liang"
  ],
  "venueShort": "JMIR Preprints",
  "venue": "JMIR Preprints (submitted to JMIR mHealth and uHealth)",
  "detail": "未經同儕審查",
  "apa": "Raj, P., Hoang, N. H., & Liang, Z. (2026). *User perspectives of an mHealth app for premenstrual syndrome (PMS) self-management: A qualitative study* [Preprint]. JMIR Preprints. https://preprints.jmir.org/preprint/105710",
  "url": "https://preprints.jmir.org/preprint/105710",
  "license": "All rights reserved",
  "licenseKind": "restricted",
  "pdf": "Raj_2026_PMSync_PMS_selfmanagement_preprint.pdf",
  "translation": "translations/Raj_2026_中文摘要整理.md",
  "translationMd": "## 研究重點\n\n這篇研究由京都先端科學大學團隊開發並評估一款名為 **PMSync** 的手機 App,專門設計用於經前症候群(PMS)的自我管理。研究動機指出:現有多數經期/生殖健康 App 主要聚焦預測「下次經期」,PMS 往往只是次要功能,且普遍缺乏協助使用者「詮釋週期性症狀模式」或「將個人經驗脈絡化」的工具。\n\n## 方法重點\n\n- PMSync 整合五大功能模組:使用 J-DRSP(SF)量表進行 PMS 自我篩檢、症狀視覺化、週期階段覺察、日記書寫,以及 AI 生成洞見;另外還有一個可選的「伴侶檢視(partner-view)」功能。\n- 採質性探索式研究設計,結合半結構式訪談與「有聲思考(think-aloud)」互動測試,共 18 位參與者(13 位女性、5 位男性伴侶),逐字稿透過 Dovetail 平台進行主題分析。\n\n## 主要發現\n\n- PMS 相關數位工具的價值可能超越單純的經期追蹤,而是進一步支援「詮釋」「行動」與「關係性溝通」三個層面。\n- PMS 自我管理有助於提升「月經健康素養」,讓使用者能夠辨識並理解與月經週期相關的壓力或難以解釋的情緒波動。\n- **伴侶分享功能**被發現有助於突顯伴侶的情緒狀態、促進即時的相互支持——這是少數同時納入男性伴侶視角的經期科技研究。\n- 多數參與者歡迎 AI 生成建議,無論是用於自我理解或幫助伴侶理解,顯示使用者與系統之間正逐漸浮現更廣泛的「人機互動關係」,而不只是單向的數據記錄。\n\n## 對設計的啟示\n\n作者提出未來 PMS 自我管理工具的設計應支援「詮釋性意義建構(interpretive sense-making)」,而非單純的症狀紀錄,並應整合教育性內容協助使用者理解自身數據。\n\n## 與研究主題的關聯\n\n這篇是目前資料夾中**唯一一篇由日本研究團隊、聚焦 PMS(而非純經期預測)、且明確納入伴侶視角**的研究,與你先前提出的「伴侶/家人在場或知情的角色」這個延伸研究面向直接對應。其「AI 生成洞見如何被使用者及其伴侶共同詮釋」的研究設計,也正好呼應你關於「使用者如何理解 AI 健康推論」的核心問題意識——值得注意的是,這篇仍是未定稿的預印本,若要正式引用,建議之後追蹤其正式發表版本是否有實質修改。",
  "titleZh": "PMSync:經前症候群自我管理 mHealth App 的使用者觀點研究",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Raj2026/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Sameh2025",
  "type": "Review",
  "year": 2025,
  "title": "Digital phenotypes and digital biomarkers for health and diseases: A systematic review of machine learning approaches utilizing passive non-invasive signals collected via wearable devices and smartphones",
  "authors": [
   "Alireza Sameh",
   "Mehrdad Rostami",
   "Mourad Oussalah",
   "Raija Korpelainen",
   "Vahid Farrahi"
  ],
  "venueShort": "Artif. Intell. Rev.",
  "venue": "Artificial Intelligence Review",
  "detail": "Vol. 58 · Article 66",
  "apa": "Sameh, A., Rostami, M., Oussalah, M., Korpelainen, R., & Farrahi, V. (2025). Digital phenotypes and digital biomarkers for health and diseases: A systematic review of machine learning approaches utilizing passive non-invasive signals collected via wearable devices and smartphones. *Artificial Intelligence Review*, *58*, Article 66. https://doi.org/10.1007/s10462-024-11009-5",
  "doi": "10.1007/s10462-024-11009-5",
  "license": "CC BY 4.0",
  "licenseKind": "cc-by",
  "pdf": "Sameh_2025_digital_phenotypes_biomarkers_systematic_review.pdf",
  "translation": "translations/Sameh_2025_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n本篇是一篇依 PRISMA 準則並於 PROSPERO 註冊的系統性回顧,聚焦於「被動、非侵入式訊號」——也就是使用者不需主動輸入、由穿戴裝置或手機在日常生活中自動收集的資料(例如動作、心率、皮膚電活動)——如何透過機器學習被轉換成「數位表型(digital phenotype)」與「數位生物標記(digital biomarker)」,進而用於健康篩檢、疾病辨識與預後預測。作者檢索五個資料庫至 2024 年 6 月,最終納入 66 篇同儕審查期刊論文,系統性整理這些研究使用的訊號類型、機器學習方法、應用的健康結果,以及目前領域中普遍存在的方法學限制。\n\n## 方法重點\n\n- 嚴格排除「結合其他資料型態(如影像、語音、人口學資料)」的研究,只保留「純被動非侵入訊號 + 機器學習」的研究,以確保聚焦。\n- 未針對每篇原始研究進行正式的證據品質評鑑(quality assessment),作者說明理由是研究間異質性過高,難以套用單一評鑑標準。\n\n## 主要發現\n\n- 最常被預測的健康結果依序為:壓力(約 24% 的研究)、癲癇發作(約 15%)、疲勞(約 12%)、憂鬱(約 9%)、巴金森氏症等神經退化性疾病。\n- 最常使用的被動訊號類型:動作/加速度資料(約 60%)、心率(約 30%)、皮膚電活動(約 24%)。\n- 傳統機器學習方法(隨機森林、支持向量機、XGBoost 等)遠比深度學習方法常見(深度學習僅占約 16%),主要原因是樣本量普遍不足以支撐深度學習所需的資料規模,以及臨床端對模型可解釋性的要求。\n- 樣本量普遍偏小:約 68% 的研究樣本數小於 100 人,其中又有約 73% 樣本數小於 50 人。\n- 資料遺失值的處理方式、實驗設計的「自由生活情境(free-living)」程度、以及程式碼與資料集的公開程度,在納入的研究中普遍表現不佳。\n\n## 限制與批判性觀察\n\n- 本回顧本身是方法學導向的系統性整理,而非對每篇原始研究進行證據等級評鑑,讀者需自行留意個別研究的方法學強弱。\n- 因排除了「多模態融合」(被動訊號結合其他資料型態)的研究,可能低估了實務上更常見、也更貼近真實應用情境的整合式系統之表現。\n- 多數研究雖標榜「日常生活」情境收集資料,實際上仍有相當比例是在實驗室或半自由生活情境下進行,顯示「數位表型」的生態效度(ecological validity)仍待更嚴謹驗證。\n\n## 與研究主題的關聯\n\n本篇是目前對「感測訊號 → 機器學習 → 數位表型/生物標記 → 健康推論」這條技術路徑最完整的方法學盤點,適合作為「數據如何被轉換為健康推論」段落的實證基礎,尤其是其對訊號類型與 ML 方法分布的整理(對應原文 Fig. 6),可直接支持你討論「哪些身體訊號被賦予健康意義」的論述。",
  "titleZh": "數位表型與數位生物標記系統性回顧",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Sameh2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Shi2025",
  "type": "Review",
  "year": 2025,
  "title": "The diagnostic accuracy of wearable digital technology in detecting fertility window and menstrual cycles: A systematic review and Bayesian network meta-analysis",
  "authors": [
   "Yue Shi",
   "Chi Chiu Wang",
   "Yongkang Yang",
   "Qin Li",
   "Pui Wah Chung",
   "Yao Wang"
  ],
  "venueShort": "npj Digit. Med.",
  "venue": "npj Digital Medicine",
  "detail": "Vol. 8",
  "apa": "Shi, Y., Wang, C. C., Yang, Y., Li, Q., Chung, P. W., & Wang, Y. (2025). The diagnostic accuracy of wearable digital technology in detecting fertility window and menstrual cycles: A systematic review and Bayesian network meta-analysis. *npj Digital Medicine*, *8*. https://doi.org/10.1038/s41746-025-02320-8",
  "doi": "10.1038/s41746-025-02320-8",
  "license": "CC BY 4.0",
  "licenseKind": "cc-by",
  "pdf": "Shi_2025_wearable_digital_technology_fertility_window_metaanalysis.pdf",
  "translation": "translations/Shi_2025_中文摘要整理.md",
  "translationMd": "## 研究重點\n\n這是一篇系統性回顧與貝氏網絡統合分析(Bayesian network meta-analysis),評估「穿戴式數位技術(WDT)」偵測女性生育窗口與月經週期的診斷準確度,並與傳統方法(自陳基礎體溫、日曆推算法、尿液荷爾蒙檢測)進行比較。檢索至 2025 年 1 月止共 8 個資料庫,最終納入 27 篇研究(其中 13 篇應用 WDT 追蹤排卵)。\n\n## 主要發現\n\n- WDT 整體匯總準確度達 0.88(95% CI: 0.86–0.90),敏感度 0.79、特異度 0.80,明顯優於傳統日曆推算法(敏感度僅 0.45),與荷爾蒙檢測法準確度相當。\n- **遠端基礎體溫(手腕/手指皮膚溫度)是偵測生育窗口最核心的生理訊號**,匯總準確度達 0.88,優於使用者自行量測、自陳的基礎體溫方法(0.75)。\n- 結合多重生理參數(體溫、心率、心率變異度、呼吸速率、皮膚電活動等)並搭配進階演算法(如支持向量機、隱馬可夫模型等 AI 方法),準確度可進一步提升至 0.89,優於單純依賴基礎體溫的偵測方式(0.87)。\n- 目前 WDT 的預測時間窗口(通常聚焦排卵前後 ±3 天)與真實生物學上的可受孕窗口(精子存活可達 5 天、卵子存活約 24 小時)之間仍有落差,作者建議未來技術應優化預測區間,涵蓋排卵前 5 天至排卵後 24 小時。\n\n## 限制與批判性觀察(作者自述)\n\n- 納入研究在生理參數擷取方式、演算法方法、裝置形式上存在相當程度的異質性。\n- 目前所有 WDT 研究均採用夜間基礎體溫作為預測基礎,皮膚溫度易受環境因素或身體活動干擾,雖有研究顯示其能線性反映核心體溫,但仍是潛在誤差來源。\n\n## 與研究主題的關聯\n\n這篇是典型的「技術端」文獻,聚焦 WDT 的**診斷準確度**本身,完全未觸及使用者如何理解、信任或詮釋這些準確度數字所代表的健康意義——例如,當 App 顯示「準確度 88%」時,使用者實際上如何將這個統計數字轉譯為對自己身體狀態的判斷與行動決策,仍是一片空白。這篇可以作為你研究中「技術端聲稱的準確性」與「使用者端實際的意義詮釋」之間落差的具體技術對照組,尤其其作者群橫跨香港中文大學與陝西中醫藥大學,也提供了一個「亞洲研究團隊產出的技術性文獻」案例,可與偏質性的 Chen (2026) 台灣研究並列對照,凸顯「技術準確度」與「使用者詮釋」兩條研究路線目前仍彼此脫節的現況。",
  "titleZh": "穿戴式數位技術偵測生育窗口與月經週期的診斷準確度",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Shi2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Sultana2025",
  "type": "Research Article",
  "year": 2025,
  "title": "'Socheton': A culturally appropriate AI tool to support reproductive well-being",
  "authors": [
   "Sharifa Sultana",
   "Hafsah Mahzabin Chowdhury",
   "Zinnat Sultana",
   "Nervo Verdezoto"
  ],
  "venueShort": "DIS '25",
  "venue": "Proceedings of the 2025 ACM Designing Interactive Systems Conference",
  "detail": "19 pages",
  "apa": "Sultana, S., Chowdhury, H. M., Sultana, Z., & Verdezoto, N. (2025). 'Socheton': A culturally appropriate AI tool to support reproductive well-being. In *Proceedings of the 2025 ACM Designing Interactive Systems Conference*. ACM. https://doi.org/10.1145/3715336.3735725",
  "doi": "10.1145/3715336.3735725",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "Sultana_2025_Socheton_reproductive_wellbeing_Bangladesh.pdf",
  "translation": "translations/Sultana_2025_Socheton_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n全球南方地區的生殖福祉教育常面臨一個困境:許多社群將現代醫療知識視為與其文化信念不符的「錯誤資訊」或「不當語言」。作者以孟加拉為場域,進行兩階段研究:第一階段為十個月的民族誌研究(n=41),探討社會文化景觀、信仰觀念、醫療基礎設施如何影響孟加拉民眾取得優質生殖健康照護的機會,並據此訂出四項設計目標:對抗錯誤資訊、使用具文化適切性的語言、由專業人員負起可課責的內容審核、以及促進使用者的民主參與。第二階段則基於「分配正義(Distributive Justice)」模型,設計並評估名為「Socheton」的 AI 中介工具,整合醫療專業人員、AI 語言教師與社群成員共同審核與經營這個以活動為基礎的平台,並進行使用者評估研究(n=28)。\n\n## 主要發現\n\n- Socheton 的原型設計達成了設定的四項設計目標(對抗錯誤資訊、文化適切語言、可課責審核、民主參與)。\n- 然而,使用者評估發現一個關鍵警訊:**僅僅對抗錯誤資訊與不當語言,仍不足以撼動社群中保守的「群體文化(mob culture)」,甚至可能持續對尋求生殖照護的行為施以家長式管束(patronize)**——換言之,單純「破除迷思」的設計取向本身有其侷限,無法單獨解決文化污名化的結構性問題。\n- 參與者進一步建議,不應只是被動的意見回饋者,而應成為內容的共同創作者,自行決定何謂文化上適切的語言、措辭與價值觀,這樣的內容才更具真實性與課責性。\n- 研究也指出:在為孟加拉這類對信仰高度敏感的社群設計時,若沿用西方知識框架強加「規範性」的福祉指引,反而可能壓抑邊緣化社群自身的價值觀、信仰與知識體系。\n\n## 限制與批判性觀察(作者自述)\n\n- 由於生殖福祉在孟加拉是高度污名化的議題,研究採用便利抽樣(convenience sampling)招募參與者,樣本本身無法免於偏誤,作者也明確表示不對研究發現做出普遍化推論(generalization)的主張。\n- 研究未能與 LGBTQ+ 社群進行更深入的討論,儘管部分問卷回應觸及此議題面向——作者說明這類主題在孟加拉同樣高度禁忌,需要更聚焦的研究問題與研究設計才能妥善處理,已超出本研究範圍。\n\n## 與研究主題的關聯\n\n本篇提供了一個具體案例,說明「單純提供正確資訊/破除迷思」的技術介入,在面對深層文化污名與家長式權力結構時效果有限,必須進一步賦予使用者(尤其是邊緣化社群)成為內容共同創作者的能動性——這個洞見可以直接支持你研究中對「AI 健康推論需要與使用者協商、而非單向給予」這個立場的論證,也提供了「分配正義」作為設計理論框架的具體應用範例,可與 ReWA 框架(Chowdhury & Sultana, 2025)互相呼應對照。",
  "titleZh": "Socheton:支持生殖福祉的文化適切性 AI 工具",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Sultana2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Zhang2025",
  "type": "Review",
  "year": 2025,
  "title": "The comprehensive clinical benefits of digital phenotyping: From broad adoption to full impact",
  "authors": [
   "Yingbo Zhang",
   "Jiao Wang",
   "Hui Zong",
   "Rajeev K. Singla",
   "Amin Ullah",
   "Xingyun Liu",
   "Rongrong Wu",
   "Shumin Ren",
   "Bairong Shen"
  ],
  "venueShort": "npj Digit. Med.",
  "venue": "npj Digital Medicine",
  "detail": "Vol. 8 · Article 196",
  "apa": "Zhang, Y., Wang, J., Zong, H., Singla, R. K., Ullah, A., Liu, X., Wu, R., Ren, S., & Shen, B. (2025). The comprehensive clinical benefits of digital phenotyping: From broad adoption to full impact. *npj Digital Medicine*, *8*, Article 196. https://doi.org/10.1038/s41746-025-01602-5",
  "doi": "10.1038/s41746-025-01602-5",
  "license": "CC BY-NC-ND",
  "licenseKind": "cc-by-nc-nd",
  "pdf": "Zhang_2025_comprehensive_clinical_benefits_digital_phenotyping.pdf",
  "translation": "translations/Zhang_2025_中文摘要整理.md",
  "translationMd": "## 摘要重點\n\n這是一篇敘事式回顧(narrative review,而非系統性回顧),從 P4 醫學框架——預測性(Predictive)、預防性(Preventive)、個人化(Personalized)、參與式(Participatory)——出發,整理「數位表型」技術目前在臨床應用上的效益與未來方向。作者將數位表型分為六大類別資料來源:行為、生理、心理、環境、社會、醫療,並沿著 P4 架構逐一舉例說明其可能帶來的臨床價值。\n\n## 內容重點\n\n- **技術脈絡**:數位表型的核心邏輯是「智慧裝置與感測器持續、被動地收集個人在日常生活中的行為與生理資料,再透過運算分析轉譯為可解讀的健康指標」。\n- **P4 框架應用**:文章依序討論數位表型如何支援疾病早期預測(P1)、風險介入與預防(P2)、依個人狀況調整的治療與照護(P3)、以及讓病患本身更主動參與健康管理(P4)。\n- **未來展望**:後半段大篇幅延伸討論「LLM(大型語言模型)驅動的數位分身(digital twin)」在未來臨床照護中的潛在角色,屬於較具推測性的願景描述,而非既有實證整理。\n\n## 限制與批判性觀察\n\n- 全文並未說明文獻檢索策略、納入排除標準,也沒有 PRISMA 流程圖,因此讀者難以判斷所引用文獻是全面回顧還是作者精選的代表性案例,證據等級明顯弱於同主題的系統性回顧(例如 Sameh et al. 2025)。\n- 文中對「LLM-based digital twin」的討論偏向未來願景與觀點闡述,與標題所承諾的「臨床效益(clinical benefits)」之間存在一定落差,較接近 perspective 文章的性質。\n- 全文聚焦在「技術如何帶來效益」的單向敘事,並未討論使用者如何理解、詮釋或協商 AI 所給出的健康推論。\n\n## 與研究主題的關聯\n\n本篇適合用來鋪陳「身體 → 數據 → AI 推論 → 健康行動」這條敘事鏈的技術端全貌與臨床想像,但因缺乏方法學透明度,建議在引用時明確標註其為敘事回顧,並避免將其作為證據強度的主要支撐來源。",
  "titleZh": "數位表型的臨床效益全面回顧",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Zhang2025/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Zhang2026a",
  "type": "Extended Abstract",
  "year": 2026,
  "title": "Legitimizing, developing, and sustaining feminist HCI in East Asia: Challenges and opportunities",
  "authors": [
   "Runhua Zhang",
   "Ruyuan Wan",
   "Jiaqi (Ella) Li",
   "Daye Kang",
   "Yigang Qin",
   "Yijia Wang",
   "Ziqi Pan",
   "Tiffany Knearem",
   "Huamin Qu",
   "Xiaojuan Ma"
  ],
  "venueShort": "CHI EA '26",
  "venue": "Extended Abstracts of the 2026 CHI Conference on Human Factors in Computing Systems",
  "detail": "4 pages",
  "apa": "Zhang, R., Wan, R., Li, J., Kang, D., Qin, Y., Wang, Y., Pan, Z., Knearem, T., Qu, H., & Ma, X. (2026a). Legitimizing, developing, and sustaining feminist HCI in East Asia: Challenges and opportunities. In *Extended Abstracts of the 2026 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3772363.3778806",
  "doi": "10.1145/3772363.3778806",
  "license": "ACM",
  "licenseKind": "restricted",
  "pdf": "FeministHCI_EastAsia_2025.pdf",
  "translation": "translations/FeministHCI_EastAsia_2025_中文摘要整理.md",
  "translationMd": "## 內容重點\n\nFeminist HCI 由 Shaowen Bardzell 於 2010 年提出,主張將女性主義理論與價值應用於互動科技的設計、批判與評估。近年有越來越多具東亞背景的學者投入此領域,研究主題涵蓋在地化的數位女性主義實踐、受區域習俗與禁忌形塑的女性健康與福祉、以及區域經濟與性別規範下的勞動平等議題,為全球學界貢獻了具在地脈絡的知識。\n\n作者群(其中包含 Daye Kang——即先前你資料夾中 PCOS 自我民族誌論文的第一作者)指出,正是這些讓東亞觀點獨特的因素,也同時是東亞研究者面臨的生存挑戰,包括:專門資助的匱乏、女性主義研究被認為不如「生產力導向」技術有價值的污名、以及資深研究者與穩固社群網絡的不足;女性主義本身在東亞地區也常被視為具政治敏感性的議題。\n\n## 提案內容\n\n本文提出一場見面會活動,設定兩個目標:(1) 為東亞地區的 Feminist HCI 研究者提供一個具正當性的交流管道,協助建立社群;(2) 促成關於如何在東亞脈絡下「使 Feminist HCI 正當化、發展與延續」的行動導向對話。活動設計包含小組討論(依職涯階段或背景分組,使用共享的「旅程板」反思求職、尋找指導者/被指導者、爭取經費、推廣 Feminist HCI 等經驗)等環節。\n\n## 與研究主題的關聯\n\n本文本身不是實證研究,但它清楚點出了一個結構性現況:**東亞脈絡下的女性主義/女性健康科技研究,長期面臨資助不足與學術正當性不足的處境**。這可以作為你研究計畫「為何這個領域資料稀少」的背景說明,同時也提供了一份可能相關的研究者人脈起點(共同作者群橫跨港科大、康乃爾、東京科學大學等機構,皆從事東亞女性主義 HCI 相關研究,包括先前提到的 PCOS 自我民族誌作者 Daye Kang)。",
  "titleZh": "在東亞地區建立、發展與延續 Feminist HCI",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Zhang2026a/筆記.md",
  "notesMd": ""
 },
 {
  "id": "Zhang2026b",
  "type": "Research Article",
  "year": 2026,
  "title": "When LLMs enter everyday feminism on Chinese social media: Opportunities and risks for women's empowerment",
  "authors": [
   "Runhua Zhang",
   "Ziqi Pan",
   "Kangyu Yuan",
   "Qiaoyi Chen",
   "Yulin Tian",
   "Huamin Qu",
   "Xiaojuan Ma"
  ],
  "venueShort": "CHI '26",
  "venue": "Proceedings of the 2026 CHI Conference on Human Factors in Computing Systems",
  "detail": "21 pages",
  "apa": "Zhang, R., Pan, Z., Yuan, K., Chen, Q., Tian, Y., Qu, H., & Ma, X. (2026b). When LLMs enter everyday feminism on Chinese social media: Opportunities and risks for women's empowerment. In *Proceedings of the 2026 CHI Conference on Human Factors in Computing Systems*. ACM. https://doi.org/10.1145/3772318.3790616",
  "doi": "10.1145/3772318.3790616",
  "license": "CC BY-NC-ND",
  "licenseKind": "cc-by-nc-nd",
  "pdf": "Zhang_2026_LLM_everyday_feminism_Chinese_social_media.pdf",
  "translation": "translations/Zhang_2026_LLM_中文摘要整理.md",
  "translationMd": "## 研究重點\n\n「日常女性主義(everyday feminism)」指女性在日常生活中以個人化、非集體動員的方式表達處境、建立團結感的實踐。本研究聚焦中國小紅書(RedNote)平台上以「女性成長」等主題標籤展開的討論,近期 DeepSeek 生成的內容開始被使用者當作這類討論中的新聲音。鑑於 LLM 已知存在性別偏誤,本研究探討 LLM 介入日常女性主義實踐時帶來的機會與風險。作者群與先前資料夾中 `FeministHCI_EastAsia_2025` 見面會提案有多位重疊作者(Runhua Zhang、Ziqi Pan、Huamin Qu、Xiaojuan Ma),可視為同一批東亞 Feminist HCI 研究者的延伸產出。\n\n## 方法重點\n\n- 分析 430 則小紅書貼文、139 則使用者分享的 DeepSeek 回應、3,211 則留言。\n- 兩條研究主線:(RQ1) 貼文中反映的主題與態度,採內容分析法;(RQ2) DeepSeek 回應如何框架「女性成長」,採女性主義批判論述分析(Feminist Critical Discourse Analysis, FCDA)。\n- 方法論上明確引用 Bardzell & Bardzell (2011) 的 feminist HCI 方法論作為理論依據之一(與資料夾中 `BardzellBardzell_2011` 直接呼應)。\n\n## 主要發現\n\n- 多數使用者對 DeepSeek 的建議抱持歡迎態度,但女性主義批判論述分析揭露:DeepSeek 的回應經常鼓勵女性以**符合既有社會結構**的方式自我最適化——這種模式在女性主義學術傳統中常被視為一種「去賦權(disempowering)」的傾向。\n- **機會面**:LLM 可能拓寬女性線上揭露的可能性——部分使用者描述 DeepSeek 幫助她們表達原本模糊、難以言說,或認為不適合在人際場合分享的敏感議題,呼應女性主義學者 Sara Ahmed 提出「為感受命名、將處境視為問題」本身即是女性主義起點的論述。DeepSeek 也在部分情況下意外揭露結構性性別議題(如對「社會時鐘」壓力的回應),促成使用者之間的情感團結。\n- **風險面**:研究者更擔憂 LLM 的存在可能**稀釋日常女性主義所仰賴的表達能動性**——許多貼文中畫面最顯眼、篇幅最長的文字並非女性自身的敘事,而是 DeepSeek 的回應;這些建議多半是「建議式」而非「詮釋式」,往往未能充分考量形塑中國女性處境的社會政治脈絡,長期可能導致表達形式趨於標準化、失去個人敘事的細緻與多元性,與女性主義重視個人敘事與經驗多元性的立場背道而馳。\n- 留言分析顯示使用者反應分化:部分讚賞 DeepSeek 促成的情感共鳴,部分則質疑其建議的資源可行性(如「靠努力工作就能認識醫院每個科的人?」),也有使用者直接批評 DeepSeek「把網路上所有的性別刻板印象都吸收進去、又吐了回來」。\n\n## 限制與批判性觀察(作者自述)\n\n- 因小紅書資料爬取機制限制,難以完整捕捉所有相關貼文;雖建立十個新帳號收集資料,仍無法保證語料完整性。\n- 分析依賴使用者分享的 DeepSeek 截圖,有時未包含完整提示詞或對話紀錄,因此研究反映的是「DeepSeek 回應如何在公開場域流通」,而非 DeepSeek 完整的價值體系。\n- 留言分析僅涵蓋第一層留言,未延伸至多層留言串,可能遺漏使用者之間協商意義的更深層互動。\n\n## 與研究主題的關聯\n\n這篇直接補上了先前「Feminist HCI 現行趨勢」中提到的**新興交會點**——三個原本分離的領域(Feminist HCI、親密資料/表達、AI 技術)在此交會:研究對象是中國女性、探討的是日常女性主義表達、技術媒介是 LLM。它與你資料夾中 `ZhangLi_2026`(中國,虛假資訊與污名感知)、`FeministHCI_EastAsia_2025`(東亞領域建制)形成有趣的三角對照,共同勾勒出「中國/東亞 × 女性 × AI/資訊科技」這個子領域正在快速發展的樣貌,也是目前資料夾中方法論(FCDA)最貼近純粹批判女性主義論述分析的一篇。",
  "titleZh": "當 LLM 進入中國社群媒體的日常女性主義",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/Zhang2026b/筆記.md",
  "notesMd": ""
 },
 {
  "id": "ZhangLi2026",
  "type": "Research Article",
  "year": 2026,
  "title": "隱於疾病背後：虛假健康信息如何影響育齡女性就醫迴避？",
  "titleZh": "The underlying cause: How reproductive health misinformation influences doctor avoidance among Chinese women of childbearing age",
  "authors": [
   "張連珊",
   "李雪晴"
  ],
  "venueShort": "傳播與社會學刊",
  "venue": "傳播與社會學刊",
  "detail": "印行中 · 頁 1–35",
  "apa": "張連珊、李雪晴（2026）。隱於疾病背後：虛假健康信息如何影響育齡女性就醫迴避？*傳播與社會學刊*。印行中。",
  "license": "未標示",
  "licenseKind": "unknown",
  "pdf": "ZhangLi_2026_reproductive_misinformation_doctor_avoidance_China.pdf",
  "translation": "translations/ZhangLi_2026_中文摘要整理.md",
  "translationMd": "## 研究重點\n\n這是一篇量化實證研究,聚焦中國大陸育齡女性(20–49 歲),探討「生育健康虛假信息接觸」如何透過「公眾污名感知」與「自我效能感」兩個心理機制,最終導致「就醫迴避」行為。研究背景數據相當驚人:中國大陸約有三億女性面臨生殖道感染等婦科疾病困擾,但整體就診意願低,高達 42.5% 的育齡女性遭遇生育系統疾病時選擇沉默、忍耐甚至拒絕就醫。\n\n## 方法重點\n\n- 採用結構方程模型(SEM),透過專業問卷平台以配額抽樣法收集 1,000 份有效問卷(2022 年 8 月),樣本年齡結構、城鄉分布與官方人口普查數據一致,經 Kolmogorov-Smirnov 檢驗確認無顯著差異。\n- 核心理論基礎為 Link 等人(1989)的「修正標籤理論」(modified labeling theory),主張污名化透過標籤化過程引發社會心理機制,進而影響個體行為後果。\n- 測量變項包括:生育健康虛假信息接觸(13 條常見不實說法,如「服用避孕藥可以有效阻止性傳播疾病」)、公眾污名感知、自我效能感、「新聞找到我」感知(news-finds-me,即個體認為自己不需主動尋找新聞也能保持消息靈通)、就醫迴避。\n\n## 主要發現\n\n- 生育健康虛假信息接觸會顯著提升公眾污名感知,污名感知再顯著降低自我效能感、並直接提高就醫迴避傾向,形成一條「虛假信息 → 公眾污名感知 → 自我效能 → 就醫迴避」的鏈式中介路徑。\n- 值得注意的是,虛假信息接觸**並未直接**顯著影響自我效能感,必須透過公眾污名感知這個中介變項才會產生作用——顯示污名感知才是關鍵的心理樞紐,而非虛假信息本身。\n- 「新聞找到我」感知發揮顯著調節作用:持有較高「新聞找到我」感知(傾向被動接收社交網絡推送資訊、較少主動查證)的女性,虛假信息接觸與公眾污名感知之間的正向關係更為顯著;而在「新聞找到我」感知較低的女性中,這條負面路徑則不再顯著。\n\n## 限制與批判性觀察(作者自述)\n\n- 橫斷面問卷設計,變項間的因果推論仍需未來實驗或縱貫研究進一步確認。\n- 僅探討「公眾污名」,未實證檢驗「自我污名」等其他污名類型,也未區分「無心之過的虛假信息(misinformation)」與「蓄意操縱的誤導信息(disinformation)」對污名化的差異化影響。\n- 未進一步比較「已確診患病」與「未患病」群體在污名內化與因應策略上的差異。\n\n## 與研究主題的關聯\n\n這篇提供了一個明確的**量化實證機制**,說明「虛假資訊環境」如何透過污名感知這個中介變項,實際阻礙中國女性的就醫行為——這與你先前討論的台灣婦科診療研究(「生殖過度醫療化、婦科健康醫療不足」)形成有趣的對照:張連珊與李雪晴的研究解釋了「污名心理機制」如何導致女性迴避就醫,而這正可以補上你研究問題中「女性為何/如何在就醫前就已形成對自身生育數據的特定健康意義理解」這一環——污名感知很可能在女性走進診間之前,就已經預先framing了她們如何詮釋自己身體的數據與症狀。",
  "criticalFormMd": null,
  "guideMd": null,
  "notes": "intimate-data-queer/01_文獻探討/critical-form/ZhangLi2026/筆記.md",
  "notesMd": ""
 }
];
